.echo OFF

drop table if exists pageDetails;

create table pageDetails (
	_id varchar NOT NULL primary key,
	hebrewDetails varchar,
	englishDetails varchar
);

insert into pageDetails values ('home', 'קבלה בידינו שיש תרי"ג מצוות בתורה (עי'' מכות דף כ"ג ע"ב), אבל לא פירטו חז"ל איזה מצוה הכתובה בתורה נמנית. נחלקו הראשנים על מניין המצוות, וכנראה לא נלקט במקום אחד כל השיטות באופן מסודר. תכלית אתר זו להציג רוב השיטות באופן יפה.<br>למטה תמצא מצוה מקרי מרשימה קולקטיבית הנקרא "כל המצוות".', 'Our tradition teaches us that there are 613 commandments (see Makkos 23b), known as the Taryag mitzvos. However, our Sages never specified which commandments written in the Torah made the list. The Rishonim argued about the listing of the commandments, and it seems that all these opinions were never collected in an organized way. The purpose of this website is to present most of the opinions in a visually pleasing way.<br>Below, you''ll find a random mitzvah from the collective "All Mitzvos" list.');

insert into pageDetails values ('compare', 'באמצע תמצא המצוות המוסכם ביניהם, ובצדדים תמצא המצוות שהאחר חולק עליו.', 'In the middle are the mitzvos that both agree upon, and on the sides are the mitzvos the other disagrees with.');

insert into pageDetails values ('allMitzvos', 'למטה תצמא רשימה לכל מצוה ומצוה שתימצא באתר זו. בכל מצוה מבואר מי מנה אותה, וקישור לאין נמצא במניינו.', 'Below you''ll find a listing of the all the unique mitzvos that appear on this site. Each mitzvah also details who counts it, and a link to where it can be found in their listing.');

insert into pageDetails values ('rambam', 'הרב משה בן מימון, חי בין שנת 1138 לשנת 1204. הוא היה ראשון להגדיר כללים לידע איך למנות התרי"ג מצוות. הוא היה חולק בתוקף כנגד הבה"ג וההולכים אחריו. המניין שלו ההכי מובחר בעולם, למרות שטעמי הסדר שלו לא ידענו.', 'Rav Moshe ben Maimon, also known as Maimonides, lived 1138-1204. He was the first to delineate exact rules on how to categorize the Taryag mitzvos. He strongly argued against the approach of the Bahag and those who followed him. His listing has become the most popular, although the exact reasons for his ordering remains a mystery.');

insert into pageDetails values ('ramban', 'הרב נחמן בן משה, חי בין שנת 1194 לשנת 1270. הוא כתב פירוש ארוך על הספר המצוות של הרמב"ם. בדרך כלל הוא מודה להרמב"ם, אבל כשחולק עליו הוא חריף מאוד. הוא לא בכת רשימה מיוחד, אז בחרנו סדר של הרמב"ם ההכי קרוב. כנראה היה לו גירסה אחרת בספר המצוות שלו, שהוא כותב שהרמב"ם חסר שבע מצוות לא תעשה. כיון שלא נודע לנו איזה מצוות היו חסר, והוא הוסיף שבע מצוות להשלימן, נמצא שמניין שלו כלול בסך הכל תר"כ מצוות.', 'Rav Nachman ben Moshe, also known as Nachmanides, lived 1194-1270. He wrote a lengthy commentary on the Sefer HaMitzvos of the Rambam. Most of the time he agreed with the Rambam''s listing, but made it clear when he argued. He didn''t write his own listing, so we chose as close as possible the order of the Rambam. He seemed to have had a different version of Sefer HaMitzvos than we have, as he claims to be missing seven negative mitzvos of the Rambam. Since we don''t know which ones were missing, and he ends up replacing them with seven new mitzvos, his list ends up being 620 mitzvos in total.');

insert into pageDetails values ('chinuch', 'נכבת בעילום שם על ידי תלמיד חכם בברצלונה במאה ה-13. הוא השתמש במנין הרמב"ם, אבל סידרם על פי פרשת השבוע. במהדורות הקודמות היה פרוט לכל פרשה המצוות העשה, ואח"כ המצוות לא תעשה. אבל במהדורות המאוחרות הכל כרונולוגי ממש. המחבר הוסיף לבאר מי מחויב במצוה זו, מתי, איפה, ואיזה עונש על מי שמבטלה.', 'Written anonymously by a major scholar in Barcelona in the 13th century. Follows the Rambam''s listing, but arranges it according to the weekly parsha. Earlier versions listed all the positive mitzvos first and then the negative ones, but later printings made the mitzvos totally chronological. He also details who is obligated in the mitzvah, when, where, and the punishment for not following it.');

insert into pageDetails values ('semag', 'גם נודע בשם ספר מצוות גדול, נכתב על ידי הרב משה בן יעקב מקוצי. רובא דרובא סבר כמו הרמב"ם, ובמעט מצוות חולק. ספרו ג"כ ליקוט של הלכות השייכות לכל מצוה ומצוה.', 'Also known as the Sefer Mitzvos Gadol, written by Rav Moshe ben Yaakov of Coucy. By and large follows the Rambam, with a small number of deviations. His book is also a collection of laws related to each mitzvah.');

insert into pageDetails values ('bahag', 'הבה"ג היה ראשון למנות המצוות. רשימתו נכתבה בהקדמתו לספרו הלכות גדולות. יש מחלוקת מי היה המחבר, אבל ברור שהוא היה אחד מהגאונים. הוא לא ביאר איך בא למיניין זו, ואינו ברור איך לחלק אותם לתרי"ג מצוות, שלא נכתב בפסיקות. השתמשנו בחלוקת <a href="https://he.wikipedia.org/wiki/%D7%90%D7%91%D7%A8%D7%94%D7%9D_%D7%A9%D7%9E%D7%A2%D7%95%D7%9F_%D7%98%D7%A8%D7%95%D7%99%D7%91" target="_blank">הרב אברהם שמעון טרויב</a>. הבה"ג וההולכים אחריו חלקו המצוות באופן מיוחד. בראשון, 71 עונשים, לפי חומר שלהם. אח"כ 277 מצוות לא תשעה על היחיד, ואז 200 מצוות עשה על היחיד. לבסוף, 65 "פרשיות", שהבינו המפרשים שרצה לומר מצוות על הציבור.', 'The Bahag was the first to enumerate the mitzvos. His list is found in the introduction to his work, Halachos Gedolos. It is a matter of dispute who wrote the book, but it was one of the Geonim. He didn''t explain how he came to this listing, and it is also unclear exactly how to break up the list, as it was written without sentence breaks. We used the division delineated by <a href="https://he.wikipedia.org/wiki/%D7%90%D7%91%D7%A8%D7%94%D7%9D_%D7%A9%D7%9E%D7%A2%D7%95%D7%9F_%D7%98%D7%A8%D7%95%D7%99%D7%91" target="_blank">Rav Avraham Shimon Traube</a>. The Bahag and those that follow him categorize the mitzvos in a unique way. First mitzvos are listed by severity of punishment, known as 71 Onshim. Then there are 277 Negative Mitzvos for the individual, followed by 200 Positive Mitzvos for the individual. Finally, there are 65 "Parshiyos", which are understood to be mitzvos incumbent upoon the community.');