.echo OFF

drop table if exists rashbag;
drop table if exists rashbagNotes;

/**
Rav Shlomo ibn Gabirol's Azharos, as explained by Nesiv Mitzvosecha
*/
create table rashbag (
	_id integer NOT NULL primary key,
	mitzvahId integer NOT NULL unique,
	mitzvahNumber integer NOT NULL,
	azharosText varchar NOT NULL,
	foreign key (mitzvahId) references mitzvos(_id) on delete cascade
);

insert into rashbag values (1,  1,   1,  'שמר לבי מענה, היה במאד נענה, ירא האל ומנה, דבריו הישרים.\nוהוא יסלח אשמה, והוא ירבה עצמה, והוא יתן חכמה, להבין נמהרים.\nאספר תושיות, מתוקות לפיות, ואציב תלפיות, לישר העוברים.\nשמנה וארבעים, ומאתים נטועים, כמו מסמרות תקועים, מספר אברים.\nבסיני נודעו, ומרום נשמעו, ויחדו הטבעו, בתוך עשרת דברים.\nאשר התוו התוות בתיבות נשתוות, במספר המצות, ובהם נאמרים.\nוהמושיעך, והמודיעך, עד אשר לרעך, נתנם נחקרים.\nוהרעים אל קעות, בקול הפליא זועות, מקפץ על גבעות, מדלג על הרים.\nועת קרא אותם, רעדה אחזתם, ויצאה נשמתם, ברטט ושברים.\nוהוריד טל אידיו, לעמו ועבדיו, והשיב בחסדיו, נשמות לפגרים.\nאני הוצאתיך, אני הזהרתיך, אני הדרכתיך, בדרכי מישרים.');
insert into rashbag values (2,  10,  2,  'ליחד אל אים');
insert into rashbag values (3,  2,   3,  'שתי פעמים ביום');
insert into rashbag values (4,  5,   4,  'להתפלל יום יום, ערבים ושחרים.');
insert into rashbag values (5,  761, 5,  'לעבדו');
insert into rashbag values (6,  3,   6,  'ולאהבו, בלב');
insert into rashbag values (7,  6,   7,  'ולדבקה בו');
insert into rashbag values (8,  8,   8,  'ולתמך בנתיבו, פעמים ואשורים.');
insert into rashbag values (9,  9,   9,  'לקדש תעצומו');
insert into rashbag values (10, 4,   10, 'ליראה מזעמו');
insert into rashbag values (11, 7,   11, 'להשבע בשמו, בלי שוא ושקרים.');
insert into rashbag values (12, 679, 12, 'לצדק דינהו');
insert into rashbag values (13, 824, 13, 'ולרדוף צדקהו');
insert into rashbag values (14, 768, 14, 'ולשמור דתהו');
insert into rashbag values (15, 769, 15, 'ולעשות מאמרים.');
insert into rashbag values (16, 783, 16, 'דבריו שים מרפא');
insert into rashbag values (17, 895, 17, 'עלי לב גם על פה');
insert into rashbag values (18, 15,  18, 'וכתבם על ספי, מזוזות ושערים.');
insert into rashbag values (19, 11,  19, 'ושננתם תמיד, לבנך ולתלמיד');
insert into rashbag values (20, 896, 20, 'והברכות תצמיד, מאת הנגמרים');
insert into rashbag values (21, 80,  21, 'בכור בנים תפדה');
insert into rashbag values (22, 12,  22, 'וטוטפות תעדה');
insert into rashbag values (23, 235, 23, 'ובכנעני תרדה');
insert into rashbag values (24, 215, 24, 'ותמול בבשרים');
insert into rashbag values (25, 81,  25, 'ותפדה פטר חמור');
insert into rashbag values (26, 770, 26, 'והשבת תשמור');
insert into rashbag values (27, 793, 27, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (28, 794, 28, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (29, 795, 29, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (30, 796, 30, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (31, 797, 31, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (32, 798, 32, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (33, 799, 33, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (34, 800, 34, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (35, 801, 35, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (36, 802, 36, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (37, 803, 37, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (38, 804, 38, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (39, 805, 39, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (40, 806, 40, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (41, 807, 41, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (42, 808, 42, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (43, 809, 43, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (44, 810, 44, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (45, 811, 45, 'וההלל תגמור, בימים נספרים.');
insert into rashbag values (46, 14,  46, 'ועל כנפי בגדך, גדילים תעשה לך');
insert into rashbag values (47, 197, 47, 'ותלוה דל ודך, תפייס בדברים.');
insert into rashbag values (48, 19,  48, 'קבע ברכת מזון, באט ובחפזון');
insert into rashbag values (49, 164, 49, 'ולא תמצא רזון, בענוי כפורים.');
insert into rashbag values (50, 199, 50, 'עבוט עני השב, ואתך אל ישב');
insert into rashbag values (51, 194, 51, 'והגזליה תשב, ועושק מסחרים.');
insert into rashbag values (52, 209, 52, 'היה לשב עניו, לשכלו ולשניו, ותקום מפניו, בפנים נהדרים.');
insert into rashbag values (53, 832, 53, 'היה לשב עניו, לשכלו ולשניו, ותקום מפניו, בפנים נהדרים.');
insert into rashbag values (54, 851, 54, 'ותלמוד');
insert into rashbag values (55, 767, 55, 'ולמד');
insert into rashbag values (56, 210, 56, 'והוריך תכבד');
insert into rashbag values (57, 204, 57, 'ותשיב כלי אובד');
insert into rashbag values (58, 79,  58, 'ותקדיש מבכרים');
insert into rashbag values (59, 195, 59, 'והדלים תרחם');
insert into rashbag values (60, 765, 60, 'והחולים תשיחם');
insert into rashbag values (61, 764, 61, 'והאבלים תנחם');
insert into rashbag values (62, 763, 62, 'ותקבור נגזרים');
insert into rashbag values (63, 778, 63, 'ולפתוח ולתת לאביון יחתת');
insert into rashbag values (64, 779, 64, 'ולפתוח ולתת לאביון יחתת');
insert into rashbag values (65, 188, 65, 'לשמיד ולמותת, עמלק ראש צרים.');
insert into rashbag values (66, 156, 66, 'לבער מחמצת, בכלה ונחרצת');
insert into rashbag values (67, 185, 67, 'ולשרוף מפלצת, אלילים ואשרים');
insert into rashbag values (68, 772, 68, 'לענג יום מנוחה, בהשקט ובבטחה');
insert into rashbag values (69, 52,  69, 'ולחג');
insert into rashbag values (70, 54,  70, 'ולשמה');
insert into rashbag values (71, 207, 71, 'ולאהוב הגרים');
insert into rashbag values (72, 203, 72, 'והצדקה לעשות, כפי יד וכמסות, ומשאות עמוסות, להקים');
insert into rashbag values (73, 202, 73, 'ולהרים.');
insert into rashbag values (74, 205, 74, 'ותלמיד שעשועים, להדר ולהנעים, ותוכחת רעים.');
insert into rashbag values (75, 206, 75, 'ואהבת החברים.');
insert into rashbag values (76, 627, 76, 'ותומה');
insert into rashbag values (77, 831, 77, 'וענוה');
insert into rashbag values (78, 771, 78, 'ויין קידוש חדוה');
insert into rashbag values (79, 21,  79, 'ויראת מקדש');
insert into rashbag values (80, 827, 80, 'וחכמים');
insert into rashbag values (81, 211, 81, 'עם הורים.');
insert into rashbag values (82, 781, 82, 'ולמוד נאמנה, לבנים ברננה');
insert into rashbag values (83, 130, 83, 'ליתום ולאלמנה, ולוי עם רגים. שמור מעשר עני');
insert into rashbag values (84, 128, 84, 'וגם מעשר שני');
insert into rashbag values (85, 166, 85, 'וראשון');
insert into rashbag values (86, 167, 86, 'ושמיני תקדש בהדרים');
insert into rashbag values (87, 129, 87, 'ומעשר');
insert into rashbag values (88, 127, 88, 'ממעשר');
insert into rashbag values (89, 131, 89, 'וגם וידוי מעשר');
insert into rashbag values (90, 78,  90, 'ומבהמה תעשר');
insert into rashbag values (91, 144, 91, 'וראש גז מעדרים');
insert into rashbag values (92, 813, 92, 'וקדשי מתני, וגם מעשר שני, תאכלם במעוני');
insert into rashbag values (93, 133, 93, 'והחלה תרים.');
insert into rashbag values (94, 773, 94, 'וחזק מך ימוט, ולעד לא תמוט');
insert into rashbag values (95, 134, 95, 'ובשביעית תשמוט, ספיחים ונזירים.');
insert into rashbag values (96, 141, 96, 'ותשמט משאות');
insert into rashbag values (97, 776, 97, 'ושכחה');
insert into rashbag values (98, 897, 98, 'עם פאות, באילן ותבואות');
insert into rashbag values (99, 122, 99, 'ושכחה');
insert into rashbag values (100, 120, 100, 'עם פאות, באילן ותבואות');
insert into rashbag values (101, 123, 101, 'ועוללות מבצירים.');
insert into rashbag values (102, 121, 102, 'ולקט הקציר');
insert into rashbag values (103, 124, 103, 'ופרט הבציר, עזוב לבלי תציר, לדלים נארים. ואלימו הבט,');
insert into rashbag values (104, 196, 104, 'בהענק');
insert into rashbag values (105, 780, 105, 'והעבט');
insert into rashbag values (106, 94,  106, 'ותן פן תלבט, נדבות ונדרים.');
insert into rashbag values (107, 91,  107, 'שמח ואמור האח, בהחיותך האח, והנותר באח, יהושלך על אורים.');
insert into rashbag values (108, 898, 108, 'ופגול כי יבאש, ישרף באש');
insert into rashbag values (109, 55,  109, 'ופסח');
insert into rashbag values (110, 56,  110, 'בצלי אש');
insert into rashbag values (111, 158, 111, 'ומצות ומרורים.');
insert into rashbag values (112, 159, 112, 'וראשון');
insert into rashbag values (113, 160, 113, 'ושביעי, תקדש בחג ישעי');
insert into rashbag values (114, 162, 114, 'ומקרא שבועי, בבכרי קצירים.');
insert into rashbag values (115, 163, 115, 'ויום זכרון');
insert into rashbag values (116, 170, 116, 'תרועה');
insert into rashbag values (117, 165, 117, 'ויום כפור תועה');
insert into rashbag values (118, 168, 118, 'וסכה');
insert into rashbag values (119, 169, 119, 'וארבעה, צמחים נבחרים. ערבים כסמדר, ועץ עבות נהדר, ופרי עץ הדר, וכפות תמרים.');
insert into rashbag values (120, 38,  120, 'וכהן הוקם על, באלמנה יגעל, ובבתולה יבעל');
insert into rashbag values (121, 26,  121, 'וידהו ירים.');
insert into rashbag values (122, 110, 122, 'וידע העתים');
insert into rashbag values (123, 899, 123, 'לטהר סות');
insert into rashbag values (124, 900, 124, 'ובתים');
insert into rashbag values (125, 840, 125, 'ופתות הפתים');
insert into rashbag values (126, 843, 126, 'והגש מוקטרים.');
insert into rashbag values (127, 845, 127, 'ונשלח נשלוח, להקטיר');
insert into rashbag values (128, 62,  128, 'ולמלוח, לכפר ולסלוח, פשעים נעתרים.');
insert into rashbag values (129, 838, 129, 'ולצוק');
insert into rashbag values (130, 839, 130, 'ולבלבל');
insert into rashbag values (131, 846, 131, 'ולשחוט פר ויובל');
insert into rashbag values (132, 847, 132, 'ולמלוק');
insert into rashbag values (133, 848, 133, 'ולקבל');
insert into rashbag values (134, 844, 134, 'ולקמץ אזכרים.');
insert into rashbag values (135, 842, 135, 'וכן ילמד עם זה, להניף');
insert into rashbag values (136, 849, 136, 'ולהזה');
insert into rashbag values (137, 760, 137, 'והשוק והחזה, לחוקי נעצרים.');
insert into rashbag values (138, 901, 138, 'ויכין למלאכת, שרד ובעת לכתו, לבית הפרוכת, בגדים משזרים.');	
insert into rashbag values (139, 20,  139, 'ותבנית המשכן');
insert into rashbag values (140, 27,  140, 'ולחם הנתכן');
insert into rashbag values (141, 35,  141, 'ושמן המתוקן, למשחה');
insert into rashbag values (142, 902, 142, 'ולמאורים.');
insert into rashbag values (143, 874, 143, 'חנכה');
insert into rashbag values (144, 903, 144, 'ומלאכת, קטורת נסכת, ושש המערכת');
insert into rashbag values (145, 46,  145, 'ושתי ככרים');
insert into rashbag values (146, 66,  146, 'ושלמים');
insert into rashbag values (147, 67,  147, 'ומנות');
insert into rashbag values (148, 63,  148, 'ועולות');
insert into rashbag values (149, 64,  149, 'וקרבנות, ושלש מתנות, במועדים נזכרים.');
insert into rashbag values (150, 44,  150, 'והעומר לנהל');
insert into rashbag values (151, 820, 151, 'ונר שבת יהל');
insert into rashbag values (152, 16,  152, 'ופרשת הקהל');
insert into rashbag values (153, 176, 153, 'ושופטים עם שטרים.');
insert into rashbag values (154, 904, 154, 'למחקורת ריבות');
insert into rashbag values (155, 905, 155, 'נפשות ומערבות');
insert into rashbag values (156, 906, 156, 'ודין ארבע אבות, נזיקים נשמרים.');
insert into rashbag values (157, 153, 157, 'וקצב ותכונה, לחדשי השנה');
insert into rashbag values (158, 876, 158, 'ומתנות כהונה, ארבעה ועשרים.');
insert into rashbag values (159, 642, 159, 'והתקופות למלאות');
insert into rashbag values (160, 821, 160, 'ונר חנכה להעלות');
insert into rashbag values (161, 53,  161, 'ולראות ולעלות, בשני מעשרים.');
insert into rashbag values (162, 17,  162, 'להנעים חומשים');
insert into rashbag values (163, 511, 163, 'וגם להיות קדושים');
insert into rashbag values (164, 109, 164, 'ולטבול נפרשים, בעתים נגזרים.');
insert into rashbag values (165, 814, 165, 'ושבת בבהמה, ועבד עם אמה');
insert into rashbag values (166, 125, 166, 'ובכורי אדמה');
insert into rashbag values (167, 132, 167, 'ומקרא בכורים.');
insert into rashbag values (168, 208, 168, 'וזרוז מתנים, וצדק מאזנים');
insert into rashbag values (169, 647, 169, 'ומתת פי שנים, לבנים הבכורים.');
insert into rashbag values (170, 828, 170, 'וחוק איפותים, וגם מדותים');
insert into rashbag values (171, 907, 171, 'וחוק איפותים, וגם מדותים');
insert into rashbag values (172, 908, 172, 'ומוצא שפתים, ופדיון נמכרים. וחופש האמה, בסימן נכתמה');
insert into rashbag values (173, 139, 173, 'ודין ערי חומה');
insert into rashbag values (174, 138, 174, 'ובתי החצרים.');
insert into rashbag values (175, 909, 175, 'ואדם לא ידום, בנמכר על זדון, ביובל');
insert into rashbag values (176, 910, 176, 'ומת אדון, ישולח לדרורים.');
insert into rashbag values (177, 911, 177, 'וצאת עברית חפשית, ביובל');
insert into rashbag values (178, 912, 178, 'וצאת ששית');
insert into rashbag values (179, 758, 179, 'ועורות');
insert into rashbag values (180, 118, 180, 'וחמישית');
insert into rashbag values (181, 182, 181, 'והבדל שש ערים.');
insert into rashbag values (182, 913, 182, 'ודין שפחה חרופה');
insert into rashbag values (183, 181, 183, 'וסוד עגלה ערופה');
insert into rashbag values (184, 57,  184, 'ופסח לתרופה, ללא המה טהורים.');
insert into rashbag values (185, 58,  185, 'ופסח לתרופה, ללא המה טהורים.');
insert into rashbag values (186, 914, 186, 'וטהרת הדוות, במימי המקוות');
insert into rashbag values (187, 68,  187, 'ופר בא על מצות');
insert into rashbag values (188, 835, 188, 'ופר הכפורים.');
insert into rashbag values (189, 915, 189, 'וטהרת הטומאה, בקרבן הנראה');
insert into rashbag values (190, 833, 190, 'וקרבן חטאה');
insert into rashbag values (191, 877, 191, 'ומוספין עשרים.');
insert into rashbag values (192, 72,  192, 'ויורד גם עולה');
insert into rashbag values (193, 65,  193, 'וודאי גם נתלה');
insert into rashbag values (194, 869, 194, 'וחרם המופלא');
insert into rashbag values (195, 868, 195, 'וערך הנודרים.');
insert into rashbag values (196, 192, 196, 'ויד');
insert into rashbag values (197, 193, 197, 'ויתד לחפור');
insert into rashbag values (198, 161, 198, 'והעומר לספור');
insert into rashbag values (199, 148, 199, 'ואם קן הצפור, לשלח ביערים.');
insert into rashbag values (200, 97,  200, 'וכל טומאה להפלות, בשקץ');
insert into rashbag values (201, 96,  201, 'ונבילות');
insert into rashbag values (202, 916, 202, 'ואדם');
insert into rashbag values (203, 917, 203, 'עם מכלות');
insert into rashbag values (204, 98,  204, 'ומקשים');
insert into rashbag values (205, 918, 205, 'ומשקים נגרים.');
insert into rashbag values (206, 919, 206, 'והסט');
insert into rashbag values (207, 99,  207, 'ושכבת');
insert into rashbag values (208, 920, 208, 'ושכבת');
insert into rashbag values (209, 105, 209, 'ומקרה מחשבת');
insert into rashbag values (210, 889, 210, 'ויבום נעזבת');		-- Nesiv Mitzvosecha says this is Parshas Yevamin of the Bahag and not the Mitzvah of Yibum. @todo: confirm this makes sense
insert into rashbag values (211, 850, 211, 'ואגרת פורים.');
insert into rashbag values (212, 217, 212, 'וחלוץ ורוקת, לאשה נתקת');
insert into rashbag values (213, 247, 213, 'וקוץ כף מחזקת, מבושי הגברים.');
insert into rashbag values (214, 221, 214, 'ודין אשת שביה');
insert into rashbag values (215, 212, 215, 'וחוק פריה ורביה');
insert into rashbag values (216, 762, 216, 'ותלבושת עריה');
insert into rashbag values (217, 921, 217, 'ונסוך מי קרים.');
insert into rashbag values (218, 119, 218, 'וערלה והילוים');
insert into rashbag values (219, 18,  219, 'ומשנה למושלים');
insert into rashbag values (220, 200, 220, 'וביומם להשלים, שכר הנשכרים.');
insert into rashbag values (221, 893, 221, 'ברכות וקללות');
insert into rashbag values (222, 879, 222, 'ומכס');
insert into rashbag values (223, 248, 223, 'ונחלות');
insert into rashbag values (224, 892, 224, 'ושיד אבנים גדולות');
insert into rashbag values (225, 136, 225, 'ויובל לדרורים.');
insert into rashbag values (226, 59,  226, 'וחצוצרות עדה');
insert into rashbag values (227, 759, 227, 'ומורם מתודה');
insert into rashbag values (228, 922, 228, 'וטבול יולדה, מדמי המקורים.');
insert into rashbag values (229, 113, 229, 'ופרה לשרפה');
insert into rashbag values (230, 923, 230, 'וחזה לתנופה');
insert into rashbag values (231, 40,  231, 'ומעשר האיפה');
insert into rashbag values (232, 126, 232, 'התרומה להרים.');
insert into rashbag values (233, 190, 233, 'ועיר יד שולחת, למלט משחת, ועם עיר נדחת, להחריב ולהחרים. ועיר כי תסגר, באבניה תגר');
insert into rashbag values (234, 822, 234, 'ותת נבלה לגר, או מכור לנכרים.');
insert into rashbag values (235, 171, 235, 'דמי כופר תשקול');
insert into rashbag values (236, 924, 236, 'המסית תסקול, ביען הרים קול, לעבדה לאחרים.');
insert into rashbag values (237, 925, 237, 'וחולם');
insert into rashbag values (238, 180, 238, 'ועד זומם, כאחד החרימם, לבלתי ירומם, להנבא שקרים.');
insert into rashbag values (239, 926, 239, 'ובפרעות תפרע, המוציא שם רע');
insert into rashbag values (240, 927, 240, 'ואיש זב ומצורע, בהזות נטהרים.');
insert into rashbag values (241, 108, 241, 'ובזה ירפא, טמא מת או נספה');
insert into rashbag values (242, 928, 242, 'ומדיח תספה, וייראו נשארים.');
insert into rashbag values (243, 929, 243, 'וחובל בלמשה, תכסהו בושה');
insert into rashbag values (244, 147, 244, 'ודם על יבשה, תכסה בעפרים.');
insert into rashbag values (245, 223, 245, 'והסוטה תשקה, למען תנקה');
insert into rashbag values (246, 184, 246, 'ועשית מעקה, להסיר מכמורים.');
insert into rashbag values (247, 214, 247, 'וחתן כל שנתו, יהי נקי לביתו, ויאחר מתאתו, ולא יעבור דברים.');
insert into rashbag values (248, 191, 248, 'ויניף יד רמה, משוח מלחמה, לבל תפול אימה, בלב הנחגרים. אלא מצותי, ואלה חקותי, ואלה תורותי, תמימים וישרים. תחיינה מהיר, ותספנה יהיר, והמזהיר יזהיר, כזוהר המאורים. ולנזהר יקרב, בשמרם עקב רב, ובאור והנערב, ישרים מכתירים.');

insert into rashbag values (249, 249, 1,  'בצל שדי אחסה, וצדקו לא אכסה, במצות לא תעשה, ואגיד מישרים. כתובים באמונה, בעדות נאמנה, וכימי השנה, במספר נחקרים. יקרים מפנינים, עתידים וצפונים, לבת האיתנים, בעדיי קשורים. צאי נא לקראתי, אחותי רעיתי, ושמעי תורתי, ולקחי מוסרים. חשקתיך ואהב, פדיתיך מרהב, כמו תורי זהב, צרופים וטהורים. בצאתי נצבה, באלף ורבבה, וקול דודי זה בא, מדלג על הרים. אנכי יי, קראתיך בסיני, ולא יהיה על פני, לך אלהים אחרים.');
insert into rashbag values (250, 250, 2,  'ולא תעשה פסל, ברשע ובכסל, ולא תשים כסל, להקניאו בזרים.');
insert into rashbag values (251, 273, 3,  'וגור מלהבה, להביא תועבה');
insert into rashbag values (252, 260, 4,  'ולבנות מצבה');
insert into rashbag values (253, 261, 5,  'ולטעת אשרים.');
insert into rashbag values (254, 529, 6,  'וסור משמע שוא, והאמן בשוא');
insert into rashbag values (255, 310, 7,  'ולא תשא לשוא, שמותי היקרים.');
insert into rashbag values (256, 537, 8,  'ונפש לא תנקש, אשר דמה אבקש');
insert into rashbag values (257, 547, 9,  'ולא תתן מוקש, להכשיל העורים.');
insert into rashbag values (258, 930, 10, 'ומצות לא נתאף, שמור פן יחרה אף');
insert into rashbag values (259, 492, 11, 'ולגנוב לא תשאף');
insert into rashbag values (260, 513, 12, 'ולא תחמוד חברים.');
insert into rashbag values (261, 514, 13, 'ולא תחמוד חברים.');
insert into rashbag values (262, 533, 14, 'ושקר לא תענה');
insert into rashbag values (263, 504, 15, 'ויתום לא תענה');
insert into rashbag values (264, 674, 16, 'וארצך לא תזנה, כארצות הזרים.');
insert into rashbag values (265, 500, 17, 'והגר לא תונה');
insert into rashbag values (266, 501, 18, 'והגר לא תונה');
insert into rashbag values (267, 503, 19, 'והגר לא תונה');
insert into rashbag values (268, 327, 20, 'וגזית לא תבנה');
insert into rashbag values (269, 531, 21, 'ועל ריב לא תענה, לחרחר מתגרים.');
insert into rashbag values (270, 563, 22, 'אלהים לא תקלל');
insert into rashbag values (271, 311, 23, 'והשם לא תחלל');
insert into rashbag values (272, 460, 24, 'וכרמך לא תעולל');
insert into rashbag values (273, 461, 25, 'ופרט הבצירים.');
insert into rashbag values (274, 565, 26, 'לא תקלל חרש, חמסו ידרש');
insert into rashbag values (275, 466, 27, 'ולא יצמיד חורש, שורים וחמורים.');
insert into rashbag values (276, 402, 28, 'לא תאחר בבצעך, מלאתך ומדעך');
insert into rashbag values (277, 495, 29, 'ולא תעשוק רעך');
insert into rashbag values (278, 403, 30, 'ולא תאחר נדרים.');
insert into rashbag values (279, 752, 31, 'ולא תעשוק שכירך');
insert into rashbag values (280, 459, 32, 'ולא תלקט קצירך');
insert into rashbag values (281, 467, 33, 'ולא תחסום שורך, בדישו העמרים.');
insert into rashbag values (282, 754, 34, 'ולא תפאר זיתך');
insert into rashbag values (283, 458, 35, 'ולא תכלה פאתך');
insert into rashbag values (284, 498, 36, 'ולא תונה עמיתך, במקח');
insert into rashbag values (285, 499, 37, 'ודברים.');
insert into rashbag values (286, 551, 38, 'ולא תשא חטאו, אשר לבו מלאו');
insert into rashbag values (287, 550, 39, 'ולא תחשוב לשונאו, כמשטמת ערים.');
insert into rashbag values (288, 552, 40, 'ולא תקום עמך, לבל אקום ממך');
insert into rashbag values (289, 486, 41, 'ולא תלין עמך, פעולת נשכרים.');
insert into rashbag values (290, 553, 42, 'ולא תטור איבות');
insert into rashbag values (291, 931, 43, 'ולא תשאל אבות');
insert into rashbag values (292, 535, 44, 'ולא יומתו אבות, ובנים על הורים.');
insert into rashbag values (293, 276, 45, 'ולא תשמע דברי, נביא שקר מורה');
insert into rashbag values (294, 265, 46, 'ולא תהיה אחרי, מסיתים נבערים.');
insert into rashbag values (295, 502, 47, 'ועבד לא תסגיר');
insert into rashbag values (296, 741, 48, 'ופנים לא תכיר');
insert into rashbag values (297, 262, 49, 'ועל פה לא תזכיר, שם אלהים אחרים.');
insert into rashbag values (298, 270, 50, 'וכספם לא תחמד');
insert into rashbag values (299, 545, 51, 'ועל דם לא תעמד');
insert into rashbag values (300, 309, 52, 'והחדל ללמוד, שבועות לשקרים.');
insert into rashbag values (301, 932, 53, 'נצור חקי על דל, ולא תשא פני דל, ומנשך תחדל, לרבות במחירים.');
insert into rashbag values (302, 740, 54, 'ומצות לא תטה');
insert into rashbag values (303, 528, 55, 'ומצות לא תטה');
insert into rashbag values (304, 526, 56, 'ומצות לא תטה, שמור פן בה תשטה, ודין יתום מוטה, ואלמנה וגרים.');
insert into rashbag values (305, 522, 57, 'ולא תקח שחד');
insert into rashbag values (306, 536, 58, 'ולא יעיד אחד');
insert into rashbag values (307, 430, 59, 'ולא תאכל יחד, נפשות ובשרים.');
insert into rashbag values (308, 493, 60, 'ולא תחמד גזלה, אשר תוקח אפלה');
insert into rashbag values (309, 516, 61, 'ולא תחמד גזלה, אשר תוקח אפלה');
insert into rashbag values (310, 428, 62, 'ולא תאכל נבלה');
insert into rashbag values (311, 933, 63, 'וזבחי השעירים.');
insert into rashbag values (312, 429, 64, 'ולא תאכל טרפה');
insert into rashbag values (313, 388, 65, 'ותועבה הדופה');
insert into rashbag values (314, 520, 66, 'ולא תקטין איפה, להפקיע שערים.');
insert into rashbag values (315, 519, 67, 'ולא תעשה רעות, במדת קרקעות, ומשקל המעות, וגם לא במשורים.');
insert into rashbag values (316, 483, 68, 'ולא תתן אכלך, במרבית פן אכלך');
insert into rashbag values (317, 549, 69, 'ולא תרוץ רגלך, מלשני בסתרים.');
insert into rashbag values (318, 534, 70, 'ולא תשית יד עם, רשעים ומרעים');
insert into rashbag values (319, 478, 71, 'ולא תגוש רעים, ואחים כנכרים.');
insert into rashbag values (320, 462, 72, 'עזוב עומר שכחתו, ולא תשוב לקחתו, לאלמנה לתתו, וליתומים וגרים.');
insert into rashbag values (321, 470, 73, 'שנת שבע תצור');
insert into rashbag values (322, 471, 74, 'שנת שבע תצור');
insert into rashbag values (323, 473, 75, 'וביובל תעצור, ספיחים לא תקצור');
insert into rashbag values (324, 474, 76, 'ולא תבצור נזירים.');
insert into rashbag values (325, 468, 77, 'ולא תזרע תלמדך');
insert into rashbag values (326, 472, 78, 'ולא תזרע תלמדך, להוציא בו לחמך');
insert into rashbag values (327, 469, 79, 'ולא תזמור כרמך, ולא יעלה סירים.');
insert into rashbag values (328, 437, 80, 'ולא תאכל קלי, ולחם וכרמלי, בטרם תביא לי, ראשית הקצירים.');
insert into rashbag values (329, 440, 81, 'ולא תאכל ערלים, בטרם הלולים');
insert into rashbag values (330, 523, 82, 'ולא תהדר גדולים');
insert into rashbag values (331, 525, 83, 'ודלים נחפרים.');
insert into rashbag values (332, 482, 84, 'ולא תהיה כנושה, לאיש עני נקשה');
insert into rashbag values (333, 342, 85, 'ולא תתנו אשה, בעורים ושבורים.');
insert into rashbag values (334, 340, 86, 'ולא תתנו אשה, בעורים ושבורים.');
insert into rashbag values (335, 341, 87, 'ולא תתנו אשה, בעורים ושבורים.');
insert into rashbag values (336, 328, 88, 'ולא יעשה משיחי, במעלות על מזבחי');
insert into rashbag values (337, 934, 89, 'ולא יעשה משיחי, במעלות על מזבחי');
insert into rashbag values (338, 614, 90, 'ולא תזבח פסחי, באחד השערים.');

create table rashbagNotes (
	_id integer NOT NULL primary key,
	hebrewNote varChar,
	enNote varChar,
	foreign key(_id) references bahag(_id) on delete cascade
);

insert into rashbagNotes values (92, null,  'Nesiv Mitzvosecha understood the Bahag as counting only one, yet Rav Troib counted two.');
insert into rashbagNotes values (111, null, 'Rashbag uses the same expression as Bahag, and Nesiv Mitzvosecha understands it''s not referring to the mitzvah to eat matzah, but maybe it includes it.');
insert into rashbagNotes values (124, null, 'Rav Troib counts the three types of tahara from tzaraas as one mitzvah, yet the Nesiv Mitzvosecha understood the Bahag as it being three.');
insert into rashbagNotes values (138, null, 'Nesiv Mitzvosecha says muktarim refers to Haktaras HaKetores, but the Bahag doesn''t count it. He also says that there are five mitzvos listed here, but if you include this one there are six. So seemingly he doesn''t mean to include it in the counting. It''s strange though that he doesn''t explain himself.');
insert into rashbagNotes values (139, null, 'The Bahag put Parshas Mishkan, Keilim, Shemen HaMaor, Bigdei Serad, Kiddush Kohanim, Chinuch Mizbeach all together (#854), and Rashbag split them up.');
insert into rashbagNotes values (142, null, 'The Rashbag split up the Bahag''s Parsha of Menorah Oil and Incense (#855).');
insert into rashbagNotes values (146, null, 'The Rashbag splits up the Bahag''s Parsha of Olos, Menachos and Shelamim (#857).');
insert into rashbagNotes values (149, null, 'Nesiv Mitzvosecha says this is referring to the Parsha of Asham Vadai and Asham Talui. However, the Rashbag explicitly counts that later, and the Nesiv Mitzvosecha as well (#193). Nesiv Mitzvosecha also never counted the mitzvah to bring a Chatas. Therefore, we chose to assume the Rashbag was referring to that. Zohar HaRakiah also says Korbonos is referring to Chatas and Asham.');
insert into rashbagNotes values (153, null, 'Nesiv Mitzvosecha says this is the Bahag''s Parsha of Shoftim and Shotrim, but the Bahag doesn''t count such a Parsha. Rav Yerucham Fischel Perla explains that Rav Saadiah Gaon (Parsha #1) means like the Bahag, yet he calls this Parsha Shoftim and Shotrim, and Rashbag followed suit. However, since he includes less than the Bahag does, we''re equating it to the Rambam''s mitzvah of Sanhedrin.');
insert into rashbagNotes values (154, null, 'Nesiv Mitzvosecha says Rashbag took out of Bahag''s Parsha of Sanhedrin Dinei Mammonos and Dinei Nefashos.');
insert into rashbagNotes values (156, null, 'The Bahag''s version of this Parsha is counted as a negative mitzvah.');
insert into rashbagNotes values (169, null, 'Nesiv Mitzvosecha doesn''t explain which mitzvah this is referring to, and simply quotes the verse it comes from. There''s reason to believe this is referring to the Bahag''s Parsha of Mishpat HaBechora (#885), but not according to the way that Rav Troib explained it (see there). Therefore, we assumed it''s the same as the Ramban''s mitzvah. However, see what the Nesiv Mitzvosecha writes at Mitzvah #223, where he seems to ignore what he wrote here.');
insert into rashbagNotes values (171, null, 'Nesiv Mitzvosecha makes a long point of explaining how this line is referring to the mitzvah of Shilum Middos that the Bahag counts, and that it''s referring to one mitzvah. However, at the end he says this section lists three mitzvos, yet he only listed two. Without an alternative, we had to interpret his explanation of why this phrase is written in the plural as being its own mitzvah. He says the poet is teaching us to own only one measure and not a dishonest measure as well.');
insert into rashbagNotes values (172, null, 'Nesiv Mitzvosecha says Rashbag split Bahag''s Parsha of Sanhedrin and took out of it the concept of a Hebrew slave.');
insert into rashbagNotes values (173, null, 'Nesiv Mitzvosecha says this is the Bahag''s parsha #25. However, he understands that Rashbag split it in two. This essentially makes it the same as the Rambam''s #138 and #139. Therefore, we equated the two.');
insert into rashbagNotes values (182, null, 'Rav Troib understood that the Bahag''s Parshas Shifcha Charufa to be a negative mitzvah. However we see the Rashbag understood it to be a positive mitzvah.');
insert into rashbagNotes values (193, null, 'This is the Bahag''s Parshas Asham Vadai Asam Talui.');
insert into rashbagNotes values (201, null, 'Nesiv Mitzvosecha, to ensure there are 613 mitzvos, is forced to split the Bahag''s Parshas Tumas Neveilos...Umashkin into six mitzvos. Although, Rav Troib understood that to be a negative mitzvah.');
insert into rashbagNotes values (206, null, 'Nesiv Mitzvosecha says this is the Bahag''s Parshas Zav VeZavah...Shichvas Zera split into four.');
insert into rashbagNotes values (213, null, 'Nesiv Mitzvosecha didn''t really explain what the mitzvah is. He just writes that Chazal say its not literal but means pay money when someone embarrasses another. Does he mean there''s a mitzvah to pay what''s known as "boshess"? But none of the other Monei Mitzvos count this (except Rav Eliyahu HaZaken; see there). They all understand this verse to be referring to saving the life of someone being pursued. As such, we assumed that Rashbag means that as well. Although the Bahag doesn''t count a mitzvah to save someone being pursued, and he does count a mitzvah of cutting off the palm, he counts that as a negative mitzvah. It must be that the Rashbag disagrees. Rav Yeruchal Fischel Perla (Parshiyos #14) also understands Rashbag to not count a separate mitzvah of boshess. Further, later the Rashbag seems to count all five payments as one mitzvah.');
insert into rashbagNotes values (218, null, 'Nesiv Mitzvosecha seems to understand this is the Bahag''s Parshas Orlah, but Rav Troib understood that to be a negative mitzvah. As such, we equated the Rashbag with the Rambam''s Hilulim.');
insert into rashbagNotes values (223, null, 'See Mitzvah #169.');
insert into rashbagNotes values (225, null, 'Nesiv Mitzvosecha understands this to be the Parshas Yovel of the Bahag, which he says is to sanctify the Yovel year. Since Rav Troib understands it differently, we equated this with the Rambam''s #136 instead of the Bahag''s Parsha.');
insert into rashbagNotes values (227, null, 'The Zohar HaRakiah understands this to be referring to breast and thigh of offerings, but the Nesiv Mitzvosecha disagrees.');
insert into rashbagNotes values (228, null, 'Nesiv Mitzvosecha says this corresponds to the Bahag''s Parshas Yoledes, but Rav Troib understood that to be a negative mitzvah.');
insert into rashbagNotes values (239, null, 'Nesiv Mitzvosecha says this is the Bahag''s negative mitzvah #230, but in the positive.');
insert into rashbagNotes values (240, null, 'Nesiv Mitzvosecha understands Zav is mentioned here just to help the rhyming scheme.');
insert into rashbagNotes values (241, null, 'Nesiv Mitzvosecha wasn''t clear how he understood this mitzvah. It sounds like the Rambam''s Parah Adumah.');
insert into rashbagNotes values (254, null, 'Nesiv Mitzvosecha explains this mitzvah the opposite of the Rambam. He says its mainly coming to prohibit accepting Loshon Hara, and it includes a judge not listening to the claims without everyone present.');
insert into rashbagNotes values (258, null, 'Since the Rashbag counts the prohibition of relations with a married woman later with the other capital crimes, he assumes this is a prohibition without a capital punishment. He cites the gemarra in Shevuos 47b for this prohibition, and what comes with it. See Azharos Rav Eliyahu HaZaken who seems to also have understood the Bahag this way. But see Yerucham Fischel Perla''s questions on this in his Hakdamah to Minyan HaOnshin § 6.');
insert into rashbagNotes values (270, null, 'The Zohar HaRakiah understands this includes both the prohibition of cursing a Judge and Hashem, but Nesiv Mitzvosecha says this only includes cursing a Judge, as the Bahag only counts this one and not "blessing" Hashem. However, Rav Troib understood the Onesh of Megadef as referring to someone who "blesses" Hashem.');
insert into rashbagNotes values (291, null, 'Nesiv Mitzvosecha seems to understand this is the Bahag''s #208. Rav Troib undersood that to be referring to the prohibition of charms, since everything else it could refer to was already counted. Nesiv Mitzvosecha on the other hand understands the Bahag to count the two verses Deuteronomy 18:10,11 as one prohibition, this being it. It''s strange though that Rashbag would refer to it this way, but we went with his understanding.');
insert into rashbagNotes values (294, null, 'Nesiv Mitzvosecha says the Rashbag counts one mitzvah regarding an enticer to idol worship, and holds the other five are just repetitive for emphasis. He wasn''t clear which of the six the Rashbag is counting, so we chose the one that seemed most fitting.');
insert into rashbagNotes values (300, null, 'Nesiv Mitzvosecha says the verse for this is "don''t swear falsely in My name", like the Zohar HaRakiah understands. However, he says this is a mitzvah not to swear falsely about owing someone money, which is a different mitzvah altogether, with a different verse. We chose the former.');
insert into rashbagNotes values (309, null, 'Nesiv Mitzvosecha brings that the Zohar HaRakiah writes that included in not stealing is the separate prohibition for a worker not to take more food than they need from what they''re working on. He writes that although the Rambam counts this mitzvah twice, he suggests that the Rashbag only counts one. However, he doesn''t explain why.');
insert into rashbagNotes values (311, null, 'Nesiv Mitzvosecha was vague as to which mitzvah he was referring to. The Rambam counts two mitzvos relating to benefiting from idol worship. One is not to benefit, and one is not to eat/drink it. We assumed Nesiv Mitzvosecha meant the former, as he didn''t focus on eating. However, he already counted this above (#3). He also counts it again later. Rav Yerucham Fischel Perla (Lo Saaseh #174) says this is referring to lo yizbechu od es zivcheihem leshearim, and says Ata Hinchalta also counts this. However, Zohar HaRakiah also understood this to be referring to benefitting from idol worship. As such, we were forced to assume Nesiv Mitzvosecha means a new, third mitzvah.');
insert into rashbagNotes values (333, null, 'Nesiv Mitzvosecha says this is the same as Bahag''s kol mum lo yihyeh bo, although Rav Troib understood that to be like the Rambam: not to give a blemish to an offering.');
insert into rashbagNotes values (334, null, 'Nesiv Mitzvosecha says this is the same as Bahag''s iveres o shavur lo sakrivu, although Rav Troib understood that to be the prohibition of sanctifying a blemished animal.');
insert into rashbagNotes values (335, null, 'Nesiv Mitzvosecha says this is the same as Bahag''s umauch vekasus...lo sakrivu, although Rav Troib understood that to be the prohibition of sanctifying an animal with an internal blemish.');
insert into rashbagNotes values (337, null, 'There''s no reason for this to be a unique mitzvah for Rashbag, but Nesiv Mitzvosecha for some unknown reason counts two mitzvos here. He doesn''t even allude to the fact that he does this, and he seems to only describe one mitzvah. This seems to be a mistake of some sort. Our best guess was he was listing two prohibitions: not to build steps, and for Kohanim not to walk up steps.');