.echo OFF

drop table if exists semag;
drop table if exists semagNotes;

/* Mitzvah categories are:
  0  -
  1  - Miseder Nashim
  2  - Issurei Maaachalos
  3  -
  4  - Nazir
  5  -
  6  - Midkash
  7  -

  8  - 
  9  - Miseder Nashim
  10 - Hechsher Maachalos
  11 - Nezikin
  12 - Nedarim UShevuos
  13 - Mikdash
*/
create table semag (
	_id integer NOT NULL primary key,
	mitzvahId integer NOT NULL UNIQUE,
	mitzvahNumber integer NOT NULL,
	category integer,
  semagTitle varchar,
	source integer,
	foreign key (mitzvahId) references mitzvos(_id) on delete cascade,
	foreign key (source) references verses(_id) on delete cascade
);

-- Mitzvos Lo Saseh are listed first
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (1, 249,  1, 0, 'לא יהיה לך אלהים אחרים על פני'); -- Can retrieve source info from rambam when they're the same
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (2, 311,  2, 0, 'לא תחללו את שם קדשי');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (3, 313,  3, 0, 'לא תעשון כן לה'' אלהיכם');
insert into semag values (4, 682,  4, 0, 'לא תנסו את ה''', 277);	-- Derech Mitzvosecha II doesn't list this as a unique mitzvah for some reason
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (5, 550,  5, 0, 'לא תשנא את אחיך בלבבך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (6, 551,  6, 0, 'שלא להלבין פני אדם בישראל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (7, 503,  7, 0, 'שלא להונות עבד שברח מח"ל לארץ');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (8, 504,  8, 0, 'שלא לענות אלמנה ושלא לענות יתום');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (9, 549,  9, 0, 'שלא לרגל בחברו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (10, 529, 10, 0, 'לא תשא שמע שוא');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (11, 552, 11, 0, 'לא תקום');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (12, 553, 12, 0, 'לא תטור');
insert into semag values (13, 683, 13, 0, 'אפי'' זקן גדול אסור לפרוש מן התורה', 494);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (14, 258, 14, 0, 'שלא לפנות אחר ע"ז לא במחשבה ולא בדבור ולא בראייה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (15, 295, 15, 0, 'שלא לתור אחר מחשבת הלב וראיית העינים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (16, 308, 16, 0, 'שאנו מוזהרים על ברכת השם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (17, 254, 17, 0, 'ולא תעבדם');
insert into semag values (18, 684, 18, 0, 'ולא תעבדם מקרא זה ללמד על המגפף והמנשק לכל ע"ז ואפי'' שאין דרך עבודתה בכך', 513);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (19, 253, 19, 0, 'שלא להשתחות לשם ע"ז אפי'' אין דרך עבודתה בכך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (20, 250, 20, 0, 'לא תעשה לך פסל וכל תמונה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (21, 251, 21, 0, 'ואלהי מסכה לא תעשו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (22, 252, 22, 0, 'שלא לעשות צורת אדם הבולטת אף לנוי');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (23, 263, 23, 0, 'שלא להדיח בני ישראל אחר ע"ז');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (24, 272, 24, 0, 'שלא להינות בממון עיר הנדחת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (25, 271, 25, 0, 'שלא לבנות עיר הנדחת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (26, 264, 26, 0, 'שלא להסית אדם מישראל אחר ע"ז');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (27, 265, 27, 0, 'שלא לאהוב את המסית');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (28, 266, 28, 0, 'שלא לעזרו בשום עזר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (29, 267, 29, 0, 'שלא להצילו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (30, 268, 30, 0, 'שלא ילמד המוסת זכות על המסית');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (31, 269, 31, 0, 'אם יודע המוסת על המסית חובה שלא ישתוק ממנה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (32, 262, 32, 0, 'שלא להתנבא בשם עבודה זרה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (33, 276, 33, 0, 'שלא לשמוע למתנבא בשם ע"ז אפילו נתן אות או מופת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (34, 275, 34, 0, 'שלא להתנבא בשקר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (35, 277, 35, 0, 'שלא לירא מהריגת נביא שקר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (36, 284, 36, 0, 'שלא לשאול באוב');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (37, 285, 37, 0, 'שלא לשאול בידעוני');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (38, 256, 38, 0, 'שלא לעשות מעשה אוב');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (39, 257, 39, 0, 'שלא לעשות מעשה ידעוני');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (40, 255, 40, 0, 'שלא להעביר מזרעו למולך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (41, 259, 41, 0, 'שלא להקים מצבת אבן אחת');
insert into semag values (42, 685, 42, 0, 'ופסל ומצבה לא תקימו לכם', 242);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (43, 260, 43, 0, 'שלא ליתן אבן משכי'' להשתחוות עליה בפישוט ידים ורגלים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (44, 261, 44, 0, 'שלא ליטע אילן במקדש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (45, 273, 45, 0, 'שלא ליהנות מע"ז ומכל משמשיה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (46, 270, 46, 0, 'שלא ליהנות מציפוי נעבד');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (47, 296, 47, 0, 'שלא לכרות ברי'' לשבעה עממים בארצינו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (48, 298, 48, 0, 'שלא ליתן חניי'' לגוי בקרקע בא"י');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (49, 299, 49, 0, 'שלא להושיב אחד משבעה עממי'' בארצינו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (50, 278, 50, 0, 'שלא ללכת בדרכי האמורי');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (51, 281, 51, 0, 'שלא לנחש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (52, 279, 52, 0, 'שלא לקסום');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (53, 280, 53, 0, 'שלא לעונן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (54, 283, 54, 0, 'שלא לחבר חבר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (55, 282, 55, 0, 'שלא לכשף');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (56, 286, 56, 0, 'שלא לדרוש אל המתים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (57, 291, 57, 0, 'שלא לגלח בתער פאת הראש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (58, 292, 58, 0, 'שלא להשחית פאת הזקן בתער');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (59, 287, 59, 0, 'שלא יהיה כלי גבר על אשה ושלא תצא אשה בכלי זיין למלחמה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (60, 288, 60, 0, 'שלא ילבש גבר שמלת אשה ושלא יתקן איש בתיקוני אשה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (61, 289, 61, 0, 'שלא יכתוב איש בשריטה בבשרו ויקעקע ששריטה בצבע');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (62, 293, 62, 0, 'שלא ישרוט אדם בבשרו על המת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (63, 419, 63, 0, 'לא תשימו קרחה בין עיניכם למת');
insert into semag values (64, 686, 64, 0, 'השמר לך פן תשכח את ה'' אלהיך', 514);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (65, 568, 65, 0, 'וביום השביעי שבת לה'' אלהיך לא תעשה כל מלאכה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (66, 569, 66, 0, 'שלא יצא אדם חוץ לתחום בשבת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (67, 570, 67, 0, 'שלא ישרופו בית דין בשבת מי שנתחייב שריפה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (68, 577, 68, 0, 'שלא לעשות מלאכה ביה"כ');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (69, 444, 69, 0, 'שלא לאכול ולשתות ביה"כ');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (70, 571, 70, 0, 'שלא לעשות מלאכה בראשון של פסח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (71, 572, 71, 0, 'שלא לעשות מלאכה בז'' של פסח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (72, 573, 72, 0, 'שלא לעשות מלאכה בחג השבועות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (73, 574, 73, 0, 'שלא לעשות מלאכה בר"ה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (74, 575, 74, 0, 'שלא לעשות מלאכה ביום ראשון של חג הסכות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (75, 576, 75, 0, 'שלא לעשות מלאכה בשמיני החג');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (76, 445, 76, 0, 'שלא לאכול חמץ בפסח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (77, 448, 77, 0, 'לא יראה לך שאור בכל גבולך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (78, 449, 78, 0, 'שאור לא ימצא בבתיכם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (79, 446, 79, 0, 'שלא לאכול דבר שיש בו תערובות חמץ');

-- Mitzvos Lo Saseh MiSeder Nashim
insert into semag values (80, 687, 80, 1, '‪‬לא יהיה קדש מבני ישראל ולא תהיה קדשה מבנות ישראל פירש אונקלוס שלא ישא ישראל שפחה ולא תינשא בת ישראל לעבד ועניין לאו אחד הוא', 467);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (81, 510, 81, 1, 'שאר'' כסות'' ועונתה לא יגרע');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (82, 604, 82, 1, 'שלא יחזיר אדם גרושתו אחר שנשאת לאחר או נתארסה לאחר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (83, 605, 83, 1, 'שלא תנשא יבמה לאיש זר עד שתסיר רשות היבם מעליה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (84, 606, 84, 1, 'שלא יגרש האונס את אנוסתו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (85, 603, 85, 1, 'אל תחלל בתך להזנות''');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (86, 607, 86, 1, 'שלא יגרש מוציא שם רע את אשתו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (87, 352, 87, 1, 'לא יצוק עליה שמן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (88, 353, 88, 1, 'לא יתן עליה לבונה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (89, 599, 89, 1, 'שלא לגלות ערות האב עצמו יתירה על אזהרה של משכב זכור');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (90, 600, 90, 1, 'שלא לגלות ערות אחי האב עצמו יתירה על אזהרה של משכב זכור');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (91, 579, 91, 1, 'שלא לגלות ערות אשת האב');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (92, 578, 92, 1, 'שלא לגלות ערות אמו אפילו היה אנוסת אביו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (93, 591, 93, 1, 'שלא לגלות ערות אשת הבן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (94, 598, 94, 1, '[ושלא לשכב עם זכר]');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (95, 596, 95, 1, 'ובכל בהמתך לא תתן שכבתך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (96, 597, 96, 1, 'ואשה לא תעמוד לפני בהמה לרבעה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (97, 595, 97, 1, 'ואל אשת עמיתך לא תתן שכבתך לזרע לטמא'' בה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (98, 582, 98, 1, 'שלא לגלות ערות בת הבן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (99, 583, 99, 1, 'שלא לגלות ערות בת הבת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (100, 584, 100, 1, 'שלא לגלות ערות הבת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (101, 585, 101, 1, 'שלא לגלות ערות אשה ובתה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (102, 586, 102, 1, 'שלא לגלות ערות אשה ובת בנה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (103, 587, 103, 1, 'שלא לגלות ערות אשה ובת בתה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (104, 581, 104, 1, 'שלא לגלות ערות אחותו מנשואת אביו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (105, 580, 105, 1, 'שלא לגלות ערות אחותו אפי'' היא מאנוסת אביו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (106, 588, 106, 1, '[שלא לגלות ערות אחות אביו]');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (107, 589, 107, 1, '[שלא לגלות ערות אחות אמו]');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (108, 593, 108, 1, 'ואשה אל אחותה לא תקח לצרור לגלות ערותה, עליה בחיה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (109, 592, 109, 1, 'ערות אשת אחיך לא תגלה בא להזהיר אף לאחר מיתת אחיו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (110, 590, 110, 1, 'שלא לגלות ערות אשת אחי אביך אף לאחר מיתת דודו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (111, 594, 111, 1, 'אל אשה בנדת טומאתה לא תקרב לגלות ערותה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (112, 300, 112, 1, 'לא תתחתן בם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (113, 301, 113, 1, 'שלא ישא עמוני בת ישראל');
insert into semag values (114, 651, 114, 1, 'שלא ישא מואבי בת ישראל', 269);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (115, 302, 115, 1, 'שלא להרחיק זרע עשו מן הקהל אלא עד ג'' דורות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (116, 303, 116, 1, 'שלא להרחיק מצרי מלבא בקהל אלא עד ג'' דורות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (117, 602, 117, 1, 'שלא ישא ממזר בת ישראל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (118, 608, 118, 1, 'מי שנפצעו בצים שלו לא ישא בת ישראל');
insert into semag values (119, 688, 119, 1, 'מי שנכרת הגיד שלו עד שלא נשתייר מן העטרה כלום לא ישא ישראלית', 469);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (120, 609, 120, 1, 'שלא יסרס אדם זכר מאחד מכל המינים לא אדם ולא בהמה ולא עוף');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (121, 406, 121, 1, 'שלא ישא כהן זונה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (122, 407, 122, 1, 'שלא ישא כהן חללה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (123, 408, 123, 1, 'שלא ישא כהן גרושה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (124, 409, 124, 1, 'שלא ישא כהן גדול אלמנה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (125, 410, 125, 1, 'שלא יבעול כהן אלמנה אפי'' בלא קידושין מפני שמחללה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (126, 601, 126, 1, 'שלא לקרב לעריות בדברים המביאין לידי גילוי ערוה כגון חיבוק ונישוק');

-- Mitzvos Lo Saseh shel Issurei Maachalos
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (127, 420, 127, 2, '‪‬שלא לאכול בהמה טמאה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (128, 422, 128, 2, 'שלא לאכול עוף טמא');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (129, 421, 129, 2, 'של לאכול דג טמא');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (130, 423, 130, 2, 'שלא לאכול חגב טמא');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (131, 424, 131, 2, 'שלא לאכול שרץ הארץ');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (132, 427, 132, 2, 'שלא לאכול שרץ המים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (133, 428, 133, 2, 'שלא לאכול מבהמה שמתה מאליה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (134, 429, 134, 2, 'שלא לאכול טרפה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (135, 436, 135, 2, 'שור הנסקל לא יאכל את בשרו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (136, 430, 136, 2, 'שלא לאכול אבר מן החי');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (137, 432, 137, 2, 'וכל דם לא תאכלו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (138, 433, 138, 2, 'כל חלב שור וכשב ועז לא תאכלו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (139, 431, 139, 2, 'לא יאכלו בני ישראל גיד הנשה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (140, 434, 140, 2, 'לא תבשל גדי בחלב אמו שלשה פעמים ותנ'' רבי ישמעאל אחד לאיסור אכילה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (141, 435, 141, 2, '[לא תבשל גדי בחלב אמו] ואחד לאיסור הנאה ואחד לאיסור בישול');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (142, 437, 142, 2, 'שלא לאכול פת מתבואה חדשה קודם הפסח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (143, 438, 143, 2, 'שלא לאכול קלי מן החדש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (144, 439, 144, 2, 'שלא לאכול כרמל מתבואה חדשה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (145, 441, 145, 2, 'שלא לאכול כלאי הכרם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (146, 440, 146, 2, 'שלא לאכול ערלה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (147, 401, 147, 2, 'שלא לאכול טבל והטבל הוא דבר שחייב בתרומות ומעשרות ולא הוציא ממנו תרומה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (148, 442, 148, 2, 'שלא לאכול תקרובת ע"ז ולא לשתות יין נסיכם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (149, 349, 149, 2, 'ושור או שה אותו ואת בנו לא תשחטו ביום אחד');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (150, 554, 150, 2, 'לא תקח האם על בנים');

insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (151, 519, 151, 3, 'לא תעשו עול במשפט במדה ובמשקל ובמשורה במשפט המדות רוצה לומר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (152, 520, 152, 3, 'שלא ישהא אדם בביתו מדה חסרה או משקל חסר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (153, 494, 153, 3, 'שלא להשיג גבול רעך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (154, 491, 154, 3, 'שלא לגנוב נפש מישראל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (155, 492, 155, 3, 'שלא לגנוב ממון');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (156, 495, 156, 3, 'מי שבא לידו ממון הבעלים ברצונם שלא לעכבו');
insert into semag values (157, 689, 157, 3, 'כל המחזיק במחלוקת עובר בלאו', 509);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (158, 513, 158, 3, 'לא תחמוד');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (159, 517, 159, 3, 'לא תוכל להתעלם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (160, 537, 160, 3, 'לא תרצח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (161, 543, 161, 3, 'לא תקחו כופר לנפש רוצח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (162, 544, 162, 3, 'שלא ליקח כופר להציל מגלות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (163, 540, 163, 3, 'רוצח שהרג בזדון אין ממיתין אותן עד שידונו אותו בית דין');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (164, 541, 164, 3, 'שלא לחוס על הרודף');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (165, 545, 165, 3, 'לא תעמוד על דם רעך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (166, 557, 166, 3, 'שלא לעבוד ולזרוע בנחל איתן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (167, 546, 167, 3, 'שלא להני'' מכשל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (168, 547, 168, 3, 'שלא להכשיל תם בדרך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (169, 518, 169, 3, 'שלא נוכל להתעלם מלעזור כאשר יראה בהמת חברו הטעונה נופלת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (170, 498, 170, 3, 'וכי תמכרו ממכר לעמיתך או קנה מיד עמיתך אל תונו איש את אחיו ותניא בתורת כהנים באונאת ממון הכתוב מדבר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (171, 499, 171, 3, 'ולא תונו איש את עמיתו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (172, 500, 172, 3, 'וגר לא (תונו)[תונה]');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (173, 501, 173, 3, 'ולא תלחצנו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (174, 507, 174, 3, 'שלא לעבוד בעבד עברי בפרך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (175, 506, 175, 3, 'שלא למכור עבד עברי בהכרזה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (176, 505, 176, 3, 'שלא יעבוד בעבד עברי עבודה של גנאי');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (177, 508, 177, 3, 'שלא נניח לעבד עברי הנמכר לגוי שירדנו בפרך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (178, 481, 178, 3, 'שלא ישלח עבדו ריקם בצאתו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (179, 509, 179, 3, 'שלא ימכור אדם בתו לשפחה אחר שפחות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (180, 502, 180, 3, 'לא תסגיר עבר אל אדניו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (181, 486, 181, 3, 'שלא לאחר פעולת שכיר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (182, 516, 182, 3, 'שלא יקח השכיר יותר מאכילתו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (183, 515, 183, 3, 'שלא יקצור הפועל בדבר שדרכו לקצור ולא לבצור בדבר שדרכו לבצור לצורך אכילתו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (184, 467, 184, 3, 'שלא לחסום בהמה בשעת מלאכה בדבר שאוכלת ממנו ונהנית');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (185, 482, 185, 3, 'אם כסף תלוה את עמי את העני עמך לא תהיה לו כנושה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (186, 487, 186, 3, 'כי תשה ברעך משאת מאומה לא תבא אל ביו לעבוט עבוטו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (187, 488, 187, 3, 'שלא יאחר המשכון מבעליו העני בעת שהוא צריך לו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (188, 489, 188, 3, 'לא תחבול בגד אלמנה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (189, 490, 189, 3, 'לא יחבול רחים');
insert into semag values (190, 690, 190, 3, 'לא יחבול רכב', 399);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (191, 483, 191, 3, 'שלא להלוות בריבות לישראל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (192, 484, 192, 3, 'שלא ללוות בריבית מישראל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (193, 485, 193, 3, 'שלא להשית יד בין לוה למלוה בריבית לא להיות לא ערב ולא עד ולא לכתוב שטר ביניהם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (194, 532, 194, 3, 'שלא למנות בדיינין איש שאין בקי בדינים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (195, 530, 195, 3, 'שלא לנטות אחרי רבים בדיני נפשות אם רבו המחייבין יותר על המזכין באיש אחד עד שיהיו שנים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (196, 531, 196, 3, 'אם ידבר מופלא שבדיינין בדיני נפשות אסור לנטות מדבריו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (197, 314, 197, 3, 'שלא ילין הצלוב על העץ');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (198, 558, 198, 3, 'מכשפה לא תחיה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (199, 548, 199, 3, 'שלא להוסיף במלקות המחוייב');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (200, 538, 200, 3, 'שלא להרוג הרוצח אפי'' חרב בידו ודם מטפטף והרוג מפרפר עד שיראו שני העדים גופו של דבר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (201, 542, 201, 3, 'שלא לענוש האנוסה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (202, 527, 202, 3, 'שלא לחוס על הרוצח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (203, 525, 203, 3, 'שלא לרחם על העני בדין');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (204, 523, 204, 3, 'שלא לכבד פני גדול בדין');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (205, 521, 205, 3, 'לא תעשו עול במשפט ונא'' לא תטה משפט');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (206, 528, 206, 3, 'לא תטה משפט גר יתום');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (207, 524, 207, 3, 'שלא ירא הדיין מאדם בדין');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (208, 522, 208, 3, 'לא תקח שוחד');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (209, 563, 209, 3, 'שלא לקלל לא דיין');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (210, 564, 210, 3, 'ו(שלא לקלל) לא נשיאאו ראש או מלך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (211, 565, 211, 3, 'שלא לקלל אחד מישראל');
insert into semag values (212, 691, 212, 3, 'שלא לקלל את עצמו', 494);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (213, 536, 213, 3, 'לא יקום עד אחד באיש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (214, 534, 214, 3, 'שלא יעיד רשע');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (215, 535, 215, 3, 'שלא יעיר קרוב');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (216, 533, 216, 3, 'לא תענה ברעך עד שקר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (217, 560, 217, 3, 'שלא להמרות על פי בית דין הגדול');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (218, 566, 218, 3, 'שלא לקלל אביו ואמו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (219, 567, 219, 3, 'שלא להכות אביו ואמו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (220, 443, 220, 3, 'לא תאכלו על הדם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (221, 610, 221, 3, 'שלא למנות איש על ישראל מקהל עכו"ם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (222, 612, 222, 3, 'מלך לא ירבה לו נשים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (223, 613, 223, 3, 'ולא ירבה לו סוסים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (224, 611, 224, 3, 'וכסף וזהב לא ירבה מאד');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (225, 297, 225, 3, 'שלא להחיות אדם משבעה עממים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (226, 307, 226, 3, 'שלא להסיר מלבנו מעשה עמלק הרעה שעשה לנו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (227, 294, 227, 3, 'שלא ישובו עם מצרימה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (228, 304, 228, 3, 'שלא לקרא לשלום לעמון ומואב בתחילה בשעת המלחמה כשאר גוים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (229, 305, 229, 3, 'שלא להשחית אלני מאכל במצור');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (230, 559, 230, 3, 'שלא יתחייב חתן בדבר מצורכי רבי'' כל שנתו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (231, 306, 231, 3, 'שלא יראו ולא יפחדו אנשי הצבא מאויביה בשעת מלחמה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (232, 511, 232, 3, 'שלא למכור אשת יפת תואר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (233, 512, 233, 3, 'שלא יכבוש אשת יפת תואר לשפחה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (234, 414, 234, 3, 'שלא יטמא למת כהן הדיוט');
insert into semag values (235, 692, 235, 3, 'שלא יכנס כהן הדיוט באהל המת והתורת כהנים לימד אותה בגזירה שוה דלא יטמא האמור בכהן גדול', 344);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (236, 415, 236, 3, 'שלא יטמא כהן גדול אף לקרובים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (237, 416, 237, 3, 'שלא יכנס עם המת באהל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (238, 310, 238, 3, 'לא תשא את שם ה'' אלהיך לשוא');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (239, 309, 239, 3, 'לא תשבעו בשמי לשקר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (240, 496, 240, 3, 'שלא לכחש בממון חבירו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (241, 497, 241, 3, 'שלא לישבע על כפירת ממון חבירו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (242, 405, 242, 3, 'שלא לעבור על דברים שאדם אוסר עצמו בהם');

-- Mitzvos Lo Saseh shel Nazir
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (243, 450, 243, 4, '‪‬שלא ישתה הנזיר יין ושכר ולא שרייתו ולא חומץ שלהם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (244, 451, 244, 4, 'שלא יאכל גוף הפרי כגון ענבים לחים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (245, 452, 245, 4, 'שלא יאכל ענבים יבשים הנקראים צימוקים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (246, 453, 246, 4, 'שלא יאכל פסולת הפרי כגון החרצנים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (247, 454, 247, 4, 'שלא יאכל זגים והוא החיצון');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (248, 456, 248, 4, 'שלא יכנס באהל המת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (249, 455, 249, 4, 'שלא יטמא למתים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (250, 457, 250, 4, 'תער לא יעבור על ראשו');

insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (251, 358, 251, 5, 'שלא למכור שדה החרם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (252, 359, 252, 5, 'שלא לפדות שדה החרם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (253, 402, 253, 5, 'שלא יקדים תרומה לביכורים ולא מעשר ראשון לתרומה ולא מעשר שני לראשון');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (254, 381, 254, 5, 'שלא יאכל זר תרומה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (255, 382, 255, 5, 'שלא יאכל אפי'' תושב כהן ושכיר תרומה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (256, 385, 256, 5, 'שלא תאכל בת כהן הנשאת לזר חזה ושוק');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (257, 384, 257, 5, 'שלא יאכל כהן טמא תרומה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (258, 383, 258, 5, 'שלא יכל ערל תרומה והוא הדין לשאר קדשים רבותינו למדוה בפרק הערל בגזרה שוה דתושב ושכיר תושב ושכיר מפסח ');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (259, 389, 259, 5, 'שלא לאכול מעשר שני של דגן חוץ לירושלם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (260, 390, 260, 5, 'שלא לאכול מעשר שני של תירוש חוץ לירושלם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (261, 391, 261, 5, 'שלא לאכול מעשר שני של יצהר חוץ לירושלם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (262, 398, 262, 5, 'שלא לאכול מעשר שני בטומאה ואפי'' בירושלם עד שיפדה');
insert into semag values (263, 693, 263, 5, 'שלא לאכול קדשים באנינות', 515);
insert into semag values (264, 694, 264, 5, 'שלא להוציא מעות מעשר שני בשאר דברים שאין בהם אכילה ושתייה וסיכה', 334);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (265, 397, 265, 5, 'שלא יאכל כהן ביכורים קודם הנחה בעזרה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (266, 468, 266, 5, 'שלא לעבוד אדמה בשביעית');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (267, 469, 267, 5, 'שלא לעבוד אילן בשביעית');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (268, 470, 268, 5, 'שלא לקצור ספיחי שביעית כדרך שקוצרין בשאר השנים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (269, 471, 269, 5, 'שלא לאסוף פירות האילן בשביעית כדרך שאוספין בשאר השנים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (270, 478, 270, 5, 'שלא יתבע הלואה שעברה עליו שביעית');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (271, 479, 271, 5, 'שלא ימנע מלהלוות לעני מפני השמיטה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (272, 472, 272, 5, 'שלא לעבוד בשנת היובל עבודת קרקע');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (273, 473, 273, 5, 'שלא לקצור ספיחי יובל כשאר שנים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (274, 474, 274, 5, 'שלא לאסוף פירות יובל כאסיפת ישאר שאר שנים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (275, 475, 275, 5, 'שלא למכור שדה בארץ ישראל לצמיתות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (276, 417, 276, 5, 'שלא יקח כל שבט לוי חלק ונחלה בארץ');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (277, 418, 277, 5, 'הלא יקח כל שבט לוי חלק בביזה בשעת כיבוש הארץ');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (278, 476, 278, 5, 'שלא לשנות מגרש ערי הלוים ושדותיהן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (279, 463, 279, 5, 'שלא לזרוע כלאי זרעים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (280, 464, 280, 5, 'שלא לזרוע כלאים בכרם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (281, 465, 281, 5, 'שלא להרביע בהמה מין בשאינו מינו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (282, 466, 282, 5, 'שלא לעשות מלאכה בשני מיני בהמה כאחד');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (283, 290, 283, 5, 'לא תלבש שעטנז צמר ופשתים יחדיו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (284, 458, 284, 5, 'שלא יקצור אדם כל שדהו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (285, 459, 285, 5, 'שלא לנקוט השבלים אחת או שתים הנופלות בשעת קצירם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (286, 461, 286, 5, 'שלא ללקט פרט הכרם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (287, 460, 287, 5, 'שלא לבצור עוללות הכרם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (288, 462, 288, 5, 'שלא ליקח עומר השכחה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (289, 480, 289, 5, 'שלא יעלים עיניו מן הצדקה');

-- Mitzvos Lo Saseh Hateluyin BaMikdash
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (290, 327, 290, 6, '‪‬שלא לבנות אבני מזבח גזית');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (291, 328, 291, 6, 'שלא לפסוע על המזבח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (292, 332, 292, 6, 'שלא יסוך אדם זר בשמן המשחה שעשה משה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (293, 331, 293, 6, 'שלא לעשותם במתכונתם שמן המשחה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (294, 333, 294, 6, 'שלא לעשות כמתכונת הקטורת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (295, 329, 295, 6, 'שלא להקריב על מזבח הזהב שבהיכל כי אם הקטרת שבכל יום בלבד');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (296, 334, 296, 6, 'שלא להוציא בדי הארון כשנושאין אותו בכתף');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (297, 320, 297, 6, 'שלא יתעסקו הכהנים בעבודת לוים ולאלוים בעבודת כהנים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (298, 336, 298, 6, 'שלא יקרע פי המעיל של כהן גדול');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (299, 335, 299, 6, 'שלא יפרק אדם את החשן מעל האפוד בשעת עבודה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (300, 321, 300, 6, 'שלא יכנס במקדש ולא יורה בתורה שתויי יין');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (301, 411, 301, 6, 'שלא יגדל כהן גדול פרע לעולם שהרי תמיד הוא במקדש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (302, 412, 302, 6, 'שלא יקרע את בגדיו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (303, 316, 303, 6, 'שלא יכנס כהן גדול אל ההיכל בכל עת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (304, 325, 304, 6, 'שלא יכנסו המצורע במחנה ישראל היא ירושלים וזבים וזבות ובעלי קרי בהר הבית וטמא מת לא יכנס בעזרה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (305, 323, 305, 6, 'שלא יעבוד כהן טמא');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (306, 324, 306, 6, 'שלא יעבוד כהן טבול יום עד שיעריב שמשו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (307, 317, 307, 6, 'שלא יכנס בעל מום אפי'' בלא עבודה אל הפרוכת ואל המזבח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (308, 318, 308, 6, 'שלא יעבוד כהן בעל מום אפי'' מום עובר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (309, 322, 309, 6, 'שלא יעבוד זר במקדש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (310, 339, 310, 6, 'לא תקריבו בפרשת אמור להזהיר על הקדישן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (311, 340, 311, 6, '(לא תקריבו בפרשת אמור להזהיר על) שחיטתן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (312, 341, 312, 6, '(לא תקריבו בפרשת אמור להזהיר על) זריקת דמן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (313, 342, 313, 6, 'ואשה לא תתנו מהם להזהיר על הקטרתן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (314, 344, 314, 6, 'שלא להקריב בעל מום מיד הגוים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (315, 345, 315, 6, 'שלא ליתן מום בקדשים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (316, 348, 316, 6, 'שלא להקריב אתנן זונה');
insert into semag values (317, 656, 317, 6, 'שלא להקריב מחיר כלב', 305);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (318, 346, 318, 6, 'שלא להקטיר שאור');
insert into semag values (319, 655, 319, 6, 'שלא להקטיר דבש', 304);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (320, 347, 320, 6, 'שלא להקריב קרבן בלא מלח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (321, 394, 321, 6, 'שלא לאכול בשר העולה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (322, 386, 322, 6, 'שלא תאכל מנחת כהן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (323, 387, 323, 6, 'שלא לאכול בשר חטאת הנעשת בפני''');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (324, 395, 324, 6, 'שלא לאכול בשר קדשים קודם זריקת דמים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (325, 393, 325, 6, 'שלא יאכלו הכהנים בשר קדשי קדשים חוץ לעזרה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (326, 396, 326, 6, 'שלא יאכל זר בשר קדשי קדשים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (327, 360, 327, 6, 'שלא יבדיל בחטאת העוף');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (328, 350, 328, 6, 'שלא ליתן שמן במנחת חוטא');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (329, 351, 329, 6, 'שלא ליתן לבונה במנחת חוטא');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (330, 372, 330, 6, 'שלא לעשות שיורי מנחת חמץ');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (331, 403, 331, 6, 'שלא לאחר הנדרים והנדבות שנדר ושנדב');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (332, 337, 332, 6, 'שלא להעלות קדשים בחוץ');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (333, 338, 333, 6, 'שלא לשחוט קדשים בחוץ');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (334, 330, 334, 6, 'שלא לכתוב אש המזבח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (335, 368, 335, 6, 'שלא להותיר מבשר התודה עד הבקר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (336, 379, 336, 6, 'שלא לאכול נותר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (337, 380, 337, 6, 'שלא לאכול פיגול למדוה בגזירה שוה עון עון מנותר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (338, 378, 338, 6, 'שלא לאכול בשר קדש שנטמא');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (339, 377, 339, 6, 'שלא יאכל טמא את הקדשים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (340, 361, 340, 6, 'שלא לעבוד בקדשים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (341, 362, 341, 6, 'שלא לגזוז את הקדשים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (342, 392, 342, 6, 'שלא לאכול בשר תמים חוץ לירושלים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (343, 356, 343, 6, 'שלא לפדות בכור בהמה טהורה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (344, 357, 344, 6, 'שלא לגאול מעשר בהמה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (345, 354, 345, 6, 'שלא להמיר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (346, 355, 346, 6, 'שלא לשנות הקדשים מקדושה לקדושה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (347, 363, 347, 6, 'שלא ישחט הפסח ועדיין חמץ קיים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (348, 364, 348, 6, 'שלא ילין אמורי הפסח למזבח מלהעלות עד הבקר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (349, 366, 349, 6, 'שלא ילין מן הבשר אשר תזבח בערב ביום הראשון לבקר תניא בפסחים לימד על חגיגת ארבעה עשר שלא להותיר עד יום השלישי וזה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (350, 373, 350, 6, 'שלא לאכול מבשר הפסח נא');
insert into semag values (351, 657, 351, 6, 'שלא לאכול מבשר הפסח מבושל', 321);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (352, 371, 352, 6, 'שלא להוציא בשר הפסח מן החבור''');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (353, 376, 353, 6, 'שלא יאכל משומד מן הפסח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (354, 374, 354, 6, 'שלא להאכיל בשר פסח לגר תושב');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (355, 375, 355, 6, 'שלא יאכל ערל בפסח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (356, 369, 356, 6, 'שלא לשבור עצם בפסח ראשון');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (357, 370, 357, 6, 'שלא לשבור עצם בפסח שני');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (358, 365, 358, 6, 'שלא להותיר מבשר הפסח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (359, 367, 359, 6, 'שלא להותיר מבשר פסח שני');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (360, 404, 360, 6, 'שלא לעלות לחג בלא קרבן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (361, 477, 361, 6, 'שלא לעזוב הלוים אלא נותנין להם מתנותיהם ומשמחין אותם בכל רגל ורגל');

insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (362, 555, 362, 7, 'שלא יגלח שער הנתק');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (363, 556, 363, 7, 'שלא לתלוש סימני צרעת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (364, 561, 364, 7, 'שלא להוסיף על המצוה שבתורה לא בתורה שבכתב ולא בתורה בעל פה שהיא פירוש והוא שיאמר שהיא תוספת מן התורה כגון שיאמר על ארבעה בתים של תפילין שיש לעשות מן התורה חמשה וכן כל כיוצא בזה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (365, 562, 365, 7, 'שלא לגרוע מכל המצות האמורות בתורה כגון ארבע בתים של תפילין לעשות שלש וכן כל כיוצא בזה');

-- Mitzvos Aseh
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (366,    1, 1, 8, 'מצות עשה להאמין כי אותו שנתן לנו את התורה בהר סיני על ידי משה רבינו הוא ה'' אלקינו שהוציאנו ממצרים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (367,    2, 2, 8, 'להאמין ולשמוע הוא הקבלה שהוא אחד בשמים ובארץ ובד'' רוחות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (368,    3, 3, 8, 'ואהבת את אלהיך בכל לבבך ובכל נפשך ובכל מאודך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (369,    4, 4, 8, 'ליראה את השם הנכבד והנורא');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (370,    9, 5, 8, 'לקדש את שמו הגדול');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (371,  172, 6, 8, 'לעשות מצות נביאי האמת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (372,    8, 7, 8, 'ללכת בדרכיו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (373,    6, 8, 8, 'לדבקה בו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (374,  206, 9, 8, 'להתנהג עם חבירו כאשר יראה שחבירו מתנהג עמו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (375, 207, 10, 8, 'לאהוב הגר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (376, 205, 11, 8, 'להוכיח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (377,  11, 12, 8, 'שחייב אדם ללמד את בנו תורה ומצות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (378, 209, 13, 8, 'מפני שיבה תקום והדרת פני זקן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (379, 185, 14, 8, 'לאבד ע"ז וכל משמשיה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (380, 186, 15, 8, 'להרוג עיר הנדחת ולשרוף העיר וכל השלל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (381,  73, 16, 8, 'שישוב החוטא מחטאו ויתוודה');
insert into semag values (382, 679, 17, 8, 'לצדק הדין על כל מאורע ויחשוב כי הכל לטובתו', 511);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (383,  10, 18, 8, 'לקרות שמע ב'' פעמים בכל יום');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (384,   5, 19, 8, 'להתפלל בכל יום');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (385,  26, 20, 8, 'שיברכו הכהנים את ישראל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (386,  13, 21, 8, 'לקשור תפילין ביד');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (387,  12, 22, 8, 'לקשור תפילין בראש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (388,  15, 23, 8, 'לקבוע מזוזה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (389,  17, 24, 8, 'שיכתוב כל איש ספר תורה לעצמו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (390,  18, 25, 8, 'שיכתוב המלך ספר תורה יתר על ספר שהיה לו כשהיה הדיוט');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (391,  14, 26, 8, 'ועשו להם ציצית על כנפי בגדיהם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (392,  19, 27, 8, 'לברך אחר אכילת לחם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (393, 215, 28, 8, 'למול את הזכרים ביום השמיני');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (394, 155, 29, 8, 'זכור את יום השבת לקדשו זכרהו בקידוש היום');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (395, 154, 30, 8, 'לשבות בו ממלאכה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (396, 165, 31, 8, 'לשבות ביום הכפורים ממלאכה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (397, 164, 32, 8, 'להתענות ביום הכפורים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (398, 159, 33, 8, 'לשבות בראשון של פסח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (399, 160, 34, 8, 'לשבות בשביעי בו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (400, 162, 35, 8, 'לשבות בחג השבועות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (401, 163, 36, 8, 'לשבות בראש השנה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (402, 166, 37, 8, 'לשבות בראשון של חג הסוכות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (403, 167, 38, 8, 'לשבות בשמיני בו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (404, 156, 39, 8, 'להשבית חמץ בי"ד');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (405, 158, 40, 8, 'לאכול מצה בליל חמשה עשר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (406, 157, 41, 8, 'לספר בלילה ההוא ניסי יציאת ממצרים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (407, 170, 42, 8, 'לתקוע בשופר בראש השנה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (408, 168, 43, 8, 'בסכות תשבו שבעת ימים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (409, 169, 44, 8, 'ולקחתם לכם ביום הראשון פרי עץ הדר כפות תמרים וענף עץ עבות וערבי נחל ושמחתם לפני ה'' אלהיכם שבעת ימים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (410, 171, 45, 8, 'ליתן מחצית השקל בכל שנה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (411, 153, 46, 8, 'שיקדשו בית דין את החדש');
insert into semag values (412, 680, 47, 8, 'לחשב תקופות ומזלות ומולדות ולעבר השנים להשוות שנת החמה עם שנת הלבנה כדי שיהא פסח בחדש האביב וסכות בזמן אסיף', 512);

-- Mitzvos Aseh MiSeder Nashim
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (413, 213, 48, 9, 'לקדש אשה בכסף או בשטר או בביאה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (414, 212, 49, 9, 'לפרות ולרבות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (415, 222, 50, 9, 'לגרש אשה בשטר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (416, 216, 51, 9, 'לייבם אשת את מאב כשמת אחיו בלא זרע');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (417, 217, 52, 9, 'לחלוץ אם לא רצה לייבם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (418, 220, 53, 9, 'לדון במפתה בחמשים שקל כסף עם שאר דינין');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (419, 218, 54, 9, 'שישא האונס את אנוסתו עם שאר דינים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (420, 219, 55, 9, 'שתשב אשת מוציא שם רע תחתיו לעולם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (421, 223, 56, 9, 'לעשות לסוטה כל הכתוב בפרש, קנאות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (422,  38, 57, 9, 'שישא כהן גדול נערה בתולה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (423,  37, 58, 9, 'שיהיו הכהנים מטמאים לקרוביהם כשאר ישראל');

-- Mitzvos Aseh Shel Hechsher Maachalos
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (424, 149, 59, 10, 'לבדוק בסימני בהמה וחיה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (425, 150, 60, 10, 'לבדוק בסימני העוף עד שיבדיל בין טמא לטהור');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (426, 151, 61, 10, 'לבדוק בסימני חגבים עד שידע הטמא מן הטהור');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (427, 152, 62, 10, 'לבדוק בסימני הדגים עד שידע הטמא מן הטהור');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (428, 146, 63, 10, 'שישחוט מי שירצה לאכול בהמה חיה או עוף כהלכותיו ואחר כך יאכל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (429, 147, 64, 10, 'לכסות דם שחיטת העוף וחיה הנאכלים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (430, 148, 65, 10, 'לשלח את הקן');

-- Mitzvos Aseh Shel Nezikin
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (431, 237, 66, 11, 'לדון בנזקי קרן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (432, 240, 67, 11, 'לדון בנזקי שן ורגל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (433, 238, 68, 11, 'לדון בנזקי הבור');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (434, 241, 69, 11, 'לדון בנזקי האש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (435, 236, 70, 11, 'לדון בנזקי אדם המזיק חבריו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (436, 239, 71, 11, 'לדון בגניבה במיתה ובתשלומין');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (437, 208, 72, 11, 'לצדק המאזנים עם המשקלות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (438, 194, 73, 11, 'שחייב אדם להחזיר הגזילה שגזל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (439, 204, 74, 11, 'להשיב אבידה לישראל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (440, 225, 75, 11, 'להגלות רוצח ההורג בשגגה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (441, 182, 76, 11, 'להפריש ערי מקלט');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (442, 247, 77, 11, 'להציל הנרדף מיד הרודף');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (443, 181, 78, 11, 'לערוף העגלה ערופה כמצותה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (444, 184, 79, 11, 'לעשות מעקה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (445, 202, 80, 11, 'לעזור המשא מעל חברו או מעל בהמתו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (446, 203, 81, 11, 'להקים המשא מעל הבהמה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (447, 245, 82, 11, 'לדון בדן מקח וממכר בדברים שהוא מתקיים בהן ודברים שאינו מתקיים בהן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (448, 232, 83, 11, 'לדון בדיני קניין עבד עברי');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (449, 196, 84, 11, 'להעניק לעבד עברי ולאמה העבריה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (450, 234, 85, 11, 'לפדות אמה העבריה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (451, 233, 86, 11, 'לייעד אמר העברייה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (452, 235, 87, 11, 'לעבוד בעבד כנעני לעולם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (453, 242, 88, 11, 'לדון בדיני שומר חנם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (454, 243, 89, 11, 'לדון בדיני נושא שכר והשוכר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (455, 200, 90, 11, 'לתת שכר השכיר בזמנו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (456, 201, 91, 11, 'שיניח בעל הבית לשכיר לאכול בזמן שכירותו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (457, 244, 92, 11, 'לדון בדין השואל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (458, 197, 93, 11, 'להלות לעני');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (459, 199, 94, 11, 'הממשכן חברו בבית דין מצוה שיחזיר לו המשכון בעת שהוא צריך לו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (460, 246, 95, 11, 'לדון בדין תובע ונתבע מודה במקצת או כופר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (461, 248, 96, 11, 'לדון בדיני נחלות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (462, 176, 97, 11, 'להעמיד דיינים בכל עיר ועיר ושוטרים הרודים בעם.');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (463, 175, 98, 11, 'ללכת אחרי הרוב אם נחלקו הדיינין');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (464, 226, 99, 11, 'להיות בית דין הורגין בסייף');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (465, 227, 100, 11, 'להיות בית דין הורגין בחנק');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (466, 228, 101, 11, 'להיות בית דין שורפין באש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (467, 229, 102, 11, 'להיות בית דין סוקלין באבנים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (468, 230, 103, 11, 'לתלות מי שנתחייב תלייה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (469, 231, 104, 11, 'לקבור הנהרג ביומו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (470, 224, 105, 11, 'להלקות הרשע');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (471, 177, 106, 11, 'להשוות הבעלי דינין שלא יכבד זה יותר מזה');
insert into semag values (472, 681, 107, 11, 'מדבר שקר תרחק', 428);
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (473, 178, 108, 11, 'היודע עדות לחברו שיעיד לו בבית דין');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (474, 179, 109, 11, 'לדרוש ולחקור העדים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (475, 180, 110, 11, 'לעשות לעדים זוממים כאשר זממו לעשות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (476, 174, 111, 11, 'לשמוע לבית דין הגדול שיעמדו להם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (477, 210, 112, 11, 'כבד את אביך ואת אמך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (478, 211, 113, 11, 'איש אמו ואביו תראו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (479, 173, 114, 11, 'להעמיד להם מלך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (480, 188, 115, 11, 'להכרית זרעו של עמלק');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (481, 189, 116, 11, 'לזכור תמיד מעשיו הרעים ואריכתו בדרך');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (482, 187, 117, 11, 'להחרים שבעה עממים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (483, 190, 118, 11, 'כי תקרב אל עיר להלחם עליה וקראת אליה לשלום');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (484, 192, 119, 11, 'לתקן מקום אחד מחוץ למחנה להפנות בו ויהיה לו יתד תקועה על כלי מלחמתו שיחפור באותו יתד גומא אחת לצאת בו יחפור ויכסה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (485, 191, 120, 11, 'שיהיה כהן אחד משוח לדבר אל העם בשעת מלחמה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (486, 214, 121, 11, 'נקי יהיה לביתו שנה אחת ושמח את אשתו אשר לקח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (487, 221, 122, 11, 'לעשות ליפת תואר ככתוב בפרשה');

-- Mitzvos Aseh Hateluyos BeNedarim UvShevuos
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (488,   7, 123, 12, 'שישבע בשם מי שנתחייב שבועה בבית דין');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (489,  94, 124, 12, 'שיקיים אדם שבועתו ונדר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (490,  95, 125, 12, 'לדון בהפרת נדרים ככל הכתוב בפרשה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (491,  92, 126, 12, 'שיגדל הנזיר שער ראשו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (492,  93, 127, 12, 'שיגלח הנזיר על קרבנו כשישלים נזירותו או כשיטמא');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (493, 114, 128, 12, 'לדון בערכי אדם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (494, 115, 129, 12, 'לדון בערכי בהמה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (495, 116, 130, 12, 'לדון בערכי בתים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (496, 117, 131, 12, 'לדון בערכי שדות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (497, 145, 132, 12, 'לדון בדין מחרים נכסיו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (498, 126, 133, 12, 'להפריש תרומה גדולה לכהן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (499, 129, 134, 12, 'להיות הלוים מפרישין תרומת מעשר מן המעשר שלקחו מישראל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (500, 127, 135, 12, 'להיות ישראל מפרישין אחר תרומה גדולה אחד מעשרה. מן הנשאר ונתנו ללווים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (501, 128, 136, 12, 'להפריש מעשר שני');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (502, 119, 137, 12, 'להיות נטע רבעי קדש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (503, 131, 138, 12, 'להתודות וידוי מעשר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (504, 125, 139, 12, 'להביא ביכורים למקדש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (505, 132, 140, 12, 'לקרות על הביכורים במקדש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (506, 133, 141, 12, 'להפריש חלה לכהן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (507, 143, 142, 12, 'לתת לכהן הזרוע והלחיים והקיבה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (508, 144, 143, 12, 'לתת ראשית הגז לכהן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (509,  80, 144, 12, 'לפדות בכור אדם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (510,  81, 145, 12, 'לפדות פטר חמור');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (511,  82, 146, 12, 'לערוף פטר חמור');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (512, 135, 147, 12, 'שתשבות הארץ בשנה השביעית מעבודת קרקע');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (513, 134, 148, 12, 'שיפקיר אדם פירות שביעית');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (514, 141, 149, 12, 'להשמיט כספים בשביעית');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (515, 140, 150, 12, 'שימנו בית דין שנות היובל שבע שבע');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (516, 136, 151, 12, 'לקדש שנת החמשים בשביתה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (517, 137, 152, 12, 'לתקוע שופר בעשרה בתשרי כדי לצאת עבדים לחפשי');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (518, 138, 153, 12, 'שתחזור אחוזה ביובל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (519, 139, 154, 12, 'להיות גאולת בתי ערי חומה עד שנה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (520, 183, 155, 12, 'לתת ללוים ערים לשבת וגם הם קולטות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (521, 120, 156, 12, 'להניח פיאה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (522, 121, 157, 12, 'להניח לקט');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (523, 122, 158, 12, 'להניח עומר השכחה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (524, 123, 159, 12, 'להניח עוללות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (525, 124, 160, 12, 'להניח פרט הכרם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (526, 130, 161, 12, 'להפריש מעשר עני בשנה השלישית לשמיטה תחת מעשר שני');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (527, 195, 162, 12, 'לתת צדקה לעניים');

-- Mitzvos Aseh Shel HaMikdash
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (528,  20, 163, 13, 'לבנות בית הבחירה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (529,  21, 164, 13, 'לירא מן המקדש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (530,  22, 165, 13, 'שיהיו הכהנים והלוים שומרי המקדש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (531,  35, 166, 13, 'לעשות שמן המשחה שיהא מוכן לדברים שמושכין בו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (532,  28, 167, 13, 'לעשות הקטורת כמניין סממניה להקטירו פעמים ביום');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (533,  34, 168, 13, 'לשחת הארון על הכתף כשמוליכין אותו ממקום למקום');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (534,  23, 169, 13, 'להיות הלוים עובדים בבית המקדש להיות שוערים ומשוררים בכל יום עם הקרבן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (535,  59, 170, 13, 'שיהיו הכהנים תוקעים החצוצרות על הקרבן במועדות ובר"ח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (536,  32, 171, 13, 'לקדש זרע אהרן ולהקדימו לכל דבר שבקדושה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (537,  36, 172, 13, 'להיות הכהנים עובדין במקדש משמרות משמרות ובמועדים כאחד');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (538,  33, 173, 13, 'שיהיו הכהנים לובשים בגדי כהונה לעבודה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (539,  31, 174, 13, 'לשלח טמאים מחוץ למחנה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (540,  24, 175, 13, 'שיקדש כהן העובד ידיו ורגליו ואחר כך יעבוד');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (541,  61, 176, 13, 'שיהיו הקרבנות תמימים ממום');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (542,  86, 177, 13, 'לפדות פסולי המוקדשים ויצאו לחולין ויאכלו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (543,  60, 178, 13, 'להקריב כל הקרבנות מיום השמיני והלאה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (544,  62, 179, 13, 'למלוח הקרבנות והמנחות');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (545,  63, 180, 13, 'לעשות העולה כמשפטה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (546,  64, 181, 13, 'לעשות החטאת כמשפטו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (547,  65, 182, 13, 'לעשות האשם כמשפטו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (548,  66, 183, 13, 'לעשות השלמים כמשפטן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (549,  89, 184, 13, 'אכילת קדשים לכהנים היא מצות עשה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (550,  88, 185, 13, 'וכן אכילת שירי מנחות מצות עשה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (551,  67, 186, 13, 'לעשות כל המנחות כמצותן הכתובות בתורה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (552,  83, 187, 13, 'שיביא אדם ברגל שפגע בו תחלה כל מה שהוא חייב בין מנדרים ונדבות בין מדברים אחרים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (553,  84, 188, 13, 'להקריב כל הקרבנות בבית הבחירה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (554,  85, 189, 13, 'שיביא אדם לבית הבחירה קרבנות שנתחייב');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (555,  39, 190, 13, 'להקריב שני תמידין בכל יום');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (556,  29, 191, 13, 'להדליק בכל יום אש על המזבח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (557,  30, 192, 13, 'למשות תרומת הדשן בכל יום');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (558,  25, 193, 13, 'להדליק נרות המנורה בכל יום במקדש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (559,  40, 194, 13, 'שיקריב כהן גדל מנחה בכל יום עשירית האיפה והיא נקראת מנחת חביתי''');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (560,  41, 195, 13, 'להקריב קרבן מוסף בשבת בשני כבשים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (561,  27, 196, 13, 'להסדיר לחם ולבונה לפני ה'' בכל שבת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (562,  42, 197, 13, 'להקריב קרבן מוסף בר"ח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (563,  43, 198, 13, 'להקריב קרבן מוסף כל שבעת ימי הפסח כקרבן ר"ח שני פרים ואיל אחד ושבעה כבשים הכל עולות ושעיר חטאת נאכל');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (564,  44, 199, 13, 'להקריב ביום שני של פסח יתר על המוסף של כל יום כבש לעולה עם עומר התנופה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (565, 161, 200, 13, 'לספור תשעה וארבעים יום מיום הבאת העומר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (566,  45, 201, 13, 'להביא בחג שבועות שהוא יום חמשים קרבן מוסף כמו בפסח ור"ח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (567,  46, 202, 13, 'להקריב בחג שבועות שתי הלחם היא המנחה החדשה עם הקרבנות הבאים בגלל הלח''');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (568,  47, 203, 13, 'להקריב מוסף בר"ה מלבד מוסף ר"ח');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (569,  48, 204, 13, 'להקריב קרבן מוסף ביום הכפורים כמו בר"ה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (570,  50, 205, 13, 'להקריב קרבן הוסף בשבעת ימי החג');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (571,  51, 206, 13, 'להקריב קרבן מוסף בשמיני עצרת כמו בר"ה וביום הכפורים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (572,  91, 207, 13, 'לשרוף הנותר באש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (573,  90, 208, 13, 'לשרוף בשר קדש שנטמא');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (574,  49, 209, 13, 'שיעשה כהן גדול כל מעשה יום הכפורים האמור על הסדר כמו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (575, 118, 210, 13, 'שישלם המועל בקדשי ה'' הקרן וחומש ואשם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (576,  79, 211, 13, 'בהולד בכור בהמה טהורה לישראל שיאמר הישראל הרי הוא מקודש בקדושת בכור');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (577,  78, 212, 13, 'לעשר כל הוולדות שנולדים לאדם בכל שנה בבקר ובצאן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (578,  69, 213, 13, 'שיקריב היחיד קרבן חטאת על שגגתו בשעשה עבירה שחייבים על זדונה כרת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (579,  70, 214, 13, 'שיקריב החוטא אשם תלוי אם נסתפק לו שמא חטא או לא חטא עד שיודע לו ויביא חטאתו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (580,  71, 215, 13, 'שיקריב החוטא אשם ודאי על עבירות ידועות כגון אשם גזילות אשם מעילות אשם שפחה חרופה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (581,  72, 216, 13, 'שיביא החוטא קרבן עולה ויורד בשמיעת קול וביטוי שפתים וטומאת מקדש וקדשיו והיולדת והמצורע');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (582,  68, 217, 13, 'שיקריבו סנהדרי גדולה קרבן אם טעו והורו שלא כהלכה בעבירות החמורות שחייבים עליהן כרת ועשו הקהל כולן או רובן על פיהם');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (583,  74, 218, 13, 'להקריב הזב קרבן אחר שיטהר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (584,  75, 219, 13, 'להקריב הזבה קרבן אחר שתטהר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (585,  76, 220, 13, 'להקריב היולדות קרבן אחר שתטהר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (586,  77, 221, 13, 'להקריב המצורע קרבן אחר שיטהר');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (587,  87, 222, 13, 'הממר הקרבן שלו תהיה התמורה קדש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (588,  55, 223, 13, 'לשחוט שה תמים זכר בן שנה לשם פסח בזמנו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (589,  57, 224, 13, 'שיהיו טמאים נדחין לפסח שני בחדש השני');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (590,  56, 225, 13, 'לאכול הפסח כמשפטו בליל ט"ו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (591,  58, 226, 13, 'לאכול הפסח שני כמשפטו בליל חמשה עשר לחדש השני');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (592,  52, 227, 13, 'לחוג ברגלים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (593,  53, 228, 13, 'להתראות ברגלים במקדש');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (594,  54, 229, 13, 'לשמוח ברגלים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (595,  16, 230, 13, 'להקהל העם לשמוע תורה במוצאי שביעית');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (596, 107, 231, 13, 'שיהא המת מטמא בכל האמור בפרשת חקת');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (597, 113, 232, 13, 'לשרוף פרה אדומה כמצותה להיות אפרה מוכן');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (598, 108, 233, 13, 'שיהו מי חטאת מטהרין מטומאת מת ומטמא לאדם טהור');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (599, 101, 234, 13, 'לעשות בנגעי אדם אם להסגיר אם להחליט אם לטהר כמשפט הכתוב בפרשה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (600, 112, 235, 13, 'שיתנהג המצורע כמשפט הכתוב');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (601, 110, 236, 13, 'להיות הטהרה מן הצרעת בין צרעת אדם בין צרעת בגד בעץ ארז ואזוב ושני תולעת ושתי צפרים ומים חיים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (602, 111, 237, 13, 'שיגלח המצורע את כל שערו');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (603, 102, 238, 13, 'לעשות בנגעי בגדים כמשפט הכתוב בפרשה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (604, 103, 239, 13, 'לעשות בנגעי בתים כמשפט הכתוב בפרשה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (605, 104, 240, 13, 'שיהא הזב טמא ומטמא לאחרים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (606,  99, 241, 13, 'שתהא הנדה טמאה ומטמאה לאחרים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (607, 106, 242, 13, 'שתהא הזבה טמאה ומטמאה לאחרים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (608, 100, 243, 13, 'שתהא היולדת טמאת כנידה');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (609,  96, 244, 13, 'להיות הנבלה טמאה ומטמאה לאחרים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (610,  97, 245, 13, 'להיות שמנה שרצים טמאים ומטמאים');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (611,  98, 246, 13, 'להיות אוכלין  ומשקין מטמאין');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (612, 105, 247, 13, 'שיהא שכבת זרע טמא ומטמא');
insert into semag (_id, mitzvahId, mitzvahNumber, category, semagTitle) values (613, 109, 248, 13, 'שיטהרו כל הטמאים במים אפילו במי מקוה');

create table semagNotes (
	_id integer NOT NULL primary key,
	hebrewNote varChar,
	enNote varChar,
	foreign key(_id) references semag(_id) on delete cascade
);

insert into semagNotes values (4,   null, 'The Rambam counts this a mitzvah against testing a proven prophet, but the Semag says this is a mitzvah not to test Hashem by performing a mitzvah and seeing if they become blessed. The Mishneh LeMelech in Derech Mitzvosecha II points out this difference but for some reason doesn''t list this as one of the mitzvos which the Semag disagrees with the Rambam, but they''re very clearly different mitzvos.');
insert into semagNotes values (8,   null, 'See Derech Mitzvosecha II.');
insert into semagNotes values (10,  null, 'The Semag also includes the prohibition- against accepting loshon hara. The Rambam mentions this in  Mishneh Torah Hilchos Sanhedrin 21:7.');
insert into semagNotes values (18,  null, 'The Ramban mentions this mitzvah at the end of his Hasagos to Mitzvah Lo Saaseh 5.');
insert into semagNotes values (28,  null, 'The Semag defines this mitzvah slightly differently than the Rambam: not to help a Meisis in any way.');
insert into semagNotes values (32,  null, 'The Semag merges Rambam Lo Saaseh #14 and #26. See Derech Mitzvosecha II.');
insert into semagNotes values (85,  null, 'The Rambam sees Deuteronomy 23:18 as the source for this mitzvah, but the Semag used that verse for Mitzvah #80.');
insert into semagNotes values (112, null, 'The Semag defines this mitzvah slightly differently than the Rambam: he limits it to the seven Canaanite nations.');
insert into semagNotes values (113, null, 'Like the Ramban, the Semag splits this into two mitzvos. This one is about Ammon.');
insert into semagNotes values (118, null, 'The Rambam counts this as one mitzvah, but the Semag splits it into two. This one is about someone without beitzim.');
insert into semagNotes values (148, null, 'The Semag learns this mitzvah is forbidding eating from things used for idol worship, which includes the prohibition on drinking idol wine libations. He learns this from  Exodus 34:12. This is more like the Ramban''s understanding (see his comments on Rambam  #194), although the Ramban doesn''t count this mitzvah.');
insert into semagNotes values (157, null, 'The Semag in his remazim sounds like he''s not sure if he should count lo sisgzol or contention. In the main work he decides on the latter.');
insert into semagNotes values (158, null, 'The Semag combines Rambam''s #265 and #266.');
insert into semagNotes values (179, null, 'The Semag sounds like this mitzvah is mainly on the father not to resell his daughter to slavery after her servitude ends. The Rambam (and Chinuch) place the focus of this mitzvah on her master not to sell her to another.');
insert into semagNotes values (189, null, 'The Semag splits this mitzvah into two. This one is for a handmill.');
insert into semagNotes values (202, null, 'The Semag formulates this mitzvah more like Ramban''s shichchah #13, but he''s apparently referring to the Rambam''s mitzvah #279. In fact, the Zohar HaRakiah suggests this is one of the mitzvos that the Ramban was missing from the Rambam, so really they''re the same mitzvah. However, this doesn''t fully explain the Ramban. See Frankel edition for sources that discuss this.');
insert into semagNotes values (262, null, 'According to Derech Mitzvosecha II, the Semag counts this mitzvah, but uses Deuteronomy 12:17 as the source.');
insert into semagNotes values (263, null, 'According to Derech Mitzvosecha II, the Semag''s conclusion is to count this instead of the Rambam''s mitzvah about maaser sheni beaninus (#151).');
insert into semagNotes values (264, null, 'According to Derech Mitzvosecha II, the Semag''s conclusion is to count this instead of the Rambam''s mitzvah about misusing maaser sheni money (#152).');
insert into semagNotes values (304, null, 'The Semag combines Rambam''s mitzvos #77 and #78 into this one.');
insert into semagNotes values (308, null, 'The Semag combines Rambam''s mitzvos #70 and #71 into this one.');
insert into semagNotes values (313, null, 'The Semag combines Rambam''s mitzvos #94 and #95 into this one.');
insert into semagNotes values (316, null, 'The Semag splits the Rambam''s mitzvah #100 into two. This one is esnan zonah.');
insert into semagNotes values (318, null, 'The Semag splits the Rambam''s mitzvah #98 into two. This one is seor.');
insert into semagNotes values (350, null, 'The Semag splits the Rambam''s mitzvah #125 into two. This one is eating the korbon pesach raw.');
insert into semagNotes values (366, null, 'The Semag uses the same verse as the Rambam''s #1, but seems to understand the verse differently. See Bris Moshe ad. loc. Derech Mitzvosecha however doesn''t count this as a difference between the Rambam and the Semag.');
insert into semagNotes values (381, null, 'The Semag includes teshuvah in the mitzvah, whereas the Rambam only mentions vidui. However, in the beginning of Hilchos Teshuvah he writes like the Semag.');
insert into semagNotes values (412, null, 'This sounds like the Ramban''s calcuation of leap years, but the Semag includes calculating the molad in this mitzvah and not in Kiddush HaChodesh like the Rambam and Ramban do.');
insert into semagNotes values (413, null, 'The Rambam includes aveilus, but the Semag left it out as he holds that''s derabanan.');
insert into semagNotes values (474, null, 'The Semag left out the word "היטב" because he argues on the Rambam how extensive is the investigation.');
insert into semagNotes values (484, null, 'The Semag merges Rambam''s mitzvah #192 and #193 into one.');
insert into semagNotes values (494, null, 'The Semag uses Vayikra 27:9, unlike the Rambam who uses Vayikra 27:11.');
insert into semagNotes values (531, null, 'The Semag emphasizes making the oil whereas the Rambam emphasizes annointing the Kohanim with it.');
insert into semagNotes values (532, null, 'The Semag emphasizes making the incense whereas the Rambam emphasizes using it.');
insert into semagNotes values (535, null, 'The Rambam adds in Hilchos Taanas 1:1 to blow the trumpets at times of peril, but the Semag leaves this out.');